import type { ScienceUnit } from '../types/lesson'

export const scienceUnits: ScienceUnit[] = [
  {
    id: 'j1-fall-life-ecosystems',
    number: 'Chapter 1 · Section 1',
    title: 'Living Things and the Environment',
    description: 'Source slides 1–15: habitats, abiotic and biotic factors, and levels of organization.',
    year: 'J1',
    semester: 'Fall',
    accent: 'green',
    sourceReferences: [
      {
        id: 'src-j1-ch1-s1-source-ppt',
        type: 'presentation',
        title: 'Copy of J1 PPT.pptx',
        location: 'Google Drive / J1Science',
        driveFileId: '1STwllX6-z931Hsqst_A1FvN7xwLCVI0g',
        notes: 'Authoritative source: Chapter 1 Section 1, source slides 1–15.',
      },
    ],
  },
  {
    id: 'j1-ch1-s2-studying-populations',
    number: 'Chapter 1 · Section 2',
    title: 'Studying Populations',
    description: 'Source slides 16–34: determining population size, population change, population density, and limiting factors.',
    year: 'J1',
    semester: 'Fall',
    accent: 'cyan',
    sourceReferences: [
      {
        id: 'src-j1-ch1-s2-source-ppt',
        type: 'presentation',
        title: 'Copy of J1 PPT.pptx',
        location: 'Google Drive / J1Science',
        driveFileId: '1STwllX6-z931Hsqst_A1FvN7xwLCVI0g',
        notes: 'Authoritative source: Chapter 1 Section 2, source slides 16–34.',
      },
    ],
  },
  {
    id: 'j1-ch1-s3-interactions',
    number: 'Chapter 1 · Section 3',
    title: 'Interactions Among Living Things',
    description: 'Source slides 35–44: adaptation, niche, competition, predation, and symbiosis.',
    year: 'J1',
    semester: 'Fall',
    accent: 'amber',
    sourceReferences: [
      {
        id: 'src-j1-ch1-s3-source-ppt',
        type: 'presentation',
        title: 'Copy of J1 PPT.pptx',
        location: 'Google Drive / J1Science',
        driveFileId: '1STwllX6-z931Hsqst_A1FvN7xwLCVI0g',
        notes: 'Authoritative source: Chapter 1 Section 3, source slides 35–44.',
      },
    ],
  },
  {
    id: 'j1-ch1-s4-succession',
    number: 'Chapter 1 · Section 4',
    title: 'Changes in Communities: Ecological Succession',
    description: 'Source slides 45–53: succession, primary succession, secondary succession, and succession diagrams.',
    year: 'J1',
    semester: 'Fall',
    accent: 'violet',
    sourceReferences: [
      {
        id: 'src-j1-ch1-s4-source-ppt',
        type: 'presentation',
        title: 'Copy of J1 PPT.pptx',
        location: 'Google Drive / J1Science',
        driveFileId: '1STwllX6-z931Hsqst_A1FvN7xwLCVI0g',
        notes: 'Authoritative source: Chapter 1 Section 4, source slides 45–53.',
      },
    ],
  },
  {
    id: 'j1-ch2-biomes',
    number: 'Chapter 2.4',
    title: 'Biomes',
    description: 'Production unit: climate factors, major land biomes, adaptations and ecosystem conditions.',
    year: 'J1',
    semester: 'Fall',
    accent: 'cyan',
    sourceReferences: [
      {
        id: 'src-j1-ppt',
        type: 'presentation',
        title: 'Copy of J1 PPT.pptx',
        location: 'Google Drive / J1Science',
      },
    ],
  },
  {
    id: 'j1-fall-reactions',
    number: 'Chapter 2',
    title: 'Chemical Reactions',
    description: 'Production unit: activation energy, catalysts, and energy transfer in endothermic and exothermic reactions.',
    year: 'J1',
    semester: 'Fall',
    accent: 'violet',
    sourceReferences: [
      {
        id: 'src-j1-ch2-reactions-ppt',
        type: 'presentation',
        title: 'Copy of J1 PPT.pptx',
        location: 'Google Drive / J1Science',
        notes: 'Recovered J1 source presentation for the Chemical Reactions sequence; exact slide range still requires final source mapping.',
      },
    ],
  },
  {
    id: 'j1-spring-solutions',
    number: 'Unit 3',
    title: 'Solutions and Solubility',
    description: 'Volume, concentration, dissolving, saturation and solubility curves.',
    year: 'J1',
    semester: 'Spring / Summer',
    accent: 'violet',
    sourceReferences: [
      {
        id: 'src-j1-ppt',
        type: 'presentation',
        title: 'Copy of J1 PPT.pptx',
        location: 'Google Drive / J1Science',
      },
    ],
  },
  {
    id: 'j2-fall-atoms-bonding',
    number: 'Chapter 1.1',
    title: 'Atoms and Bonding',
    description: 'Opening unit: matter, elements, atoms, scientific models, atomic theory and the modern atom.',
    year: 'J2',
    semester: 'Fall',
    accent: 'violet',
    sourceReferences: [
      {
        id: 'src-j2-opening-source-ppt',
        type: 'presentation',
        title: 'J2 PPT (updated).pptx',
        location: 'Google Drive / J2Science',
        driveFileId: '14AUxNBq96_rRR9exiieSsHBdvuth4ofh',
        notes: 'Authoritative source for the J2 opening lesson sequence.',
      },
    ],
  },
  {
    id: 'j2-fall-ecosystems',
    number: 'Unit 2',
    title: 'Ecosystems',
    description: 'Habitats, food webs, adaptation and interactions within ecosystems.',
    year: 'J2',
    semester: 'Fall',
    accent: 'green',
    sourceReferences: [
      {
        id: 'src-j2-ppt',
        type: 'presentation',
        title: 'J2 PPT (updated).pptx',
        location: 'Google Drive / J2Science',
      },
    ],
  },
  {
    id: 'j2-spring-earth',
    number: 'Unit 3',
    title: 'Earth Systems',
    description: 'Water, weather, human impact and evidence-based environmental decisions.',
    year: 'J2',
    semester: 'Spring / Summer',
    accent: 'amber',
    sourceReferences: [
      {
        id: 'src-j2-ppt',
        type: 'presentation',
        title: 'J2 PPT (updated).pptx',
        location: 'Google Drive / J2Science',
      },
    ],
  },
]
