import type { LessonBiomeKey, LessonVisualAsset } from '../types/lesson'

export const biomesVisualAssets: Record<string, LessonVisualAsset> = {
  'biomes-blue-marble': {
    id: 'biomes-blue-marble',
    title: 'Blue Marble world map',
    type: 'map',
    origin: 'external-educational',
    localPath: '/science-lessons/biomes/earth-blue-marble.jpg',
    alt: 'NASA Blue Marble world map showing global land, ocean, ice, and vegetation patterns',
    attribution: 'NASA / Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Blue_Marble_2002.png',
    creator: 'NASA',
    organisation: 'NASA',
    license: 'Public domain / NASA imagery; verify final classroom attribution before publishing',
    retrieved: '2026-08-10',
    originalSourceId: 'src-j1-ch2-4-ppt',
    lessonIds: ['j1-ch2-4-biomes-lesson-1', 'j1-ch2-4-biomes-lesson-2'],
    slideIds: ['j1-ch2-4-title'],
    usage: 'Opening global view connecting climate patterns to biome distribution.',
  },
  'biomes-rainforest-canopy': {
    id: 'biomes-rainforest-canopy',
    title: 'Rainforest canopy near Cairns',
    type: 'photo',
    origin: 'external-educational',
    localPath: '/science-lessons/biomes/rainforest-canopy.jpg',
    alt: 'Tropical rainforest canopy near Cairns, Queensland',
    attribution: 'CSIRO / Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:CSIRO_ScienceImage_3829_Tropical_rainforest_canopy_near_Cairns_QLD.jpg',
    creator: 'CSIRO',
    organisation: 'CSIRO',
    license: 'Wikimedia Commons listed license; verify exact reuse terms before publishing',
    retrieved: '2026-08-10',
    originalSourceId: 'src-j1-ch2-4-ppt',
    lessonIds: ['j1-ch2-4-biomes-lesson-1', 'j1-ch2-4-biomes-lesson-2'],
    slideIds: ['j1-ch2-4-rain-forest', 'j1-ch2-4-rainforest-layers'],
    usage: 'Supports canopy and understory structure labels.',
  },
  'biomes-desert-sahara': {
    id: 'biomes-desert-sahara',
    title: 'Sahara desert dunes',
    type: 'photo',
    origin: 'external-educational',
    localPath: '/science-lessons/biomes/desert-sahara.jpg',
    alt: 'Sahara desert sand dunes in Tunisia',
    attribution: 'Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tunisia_Sahara.jpg',
    license: 'Wikimedia Commons listed license; verify exact reuse terms before publishing',
    retrieved: '2026-08-10',
    originalSourceId: 'src-j1-ch2-4-ppt',
    lessonIds: ['j1-ch2-4-biomes-lesson-1', 'j1-ch2-4-biomes-lesson-2'],
    slideIds: ['j1-ch2-4-desert', 'j1-ch2-4-desert-night'],
    usage: 'Provides real desert context behind precipitation and evaporation comparison.',
  },
  'biomes-grassland-savanna': {
    id: 'biomes-grassland-savanna',
    title: 'Sand prairie and oak savanna',
    type: 'photo',
    origin: 'external-educational',
    localPath: '/science-lessons/biomes/grassland-savanna.jpg',
    alt: 'Sand prairie and oak savanna grassland',
    attribution: 'Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Albany_Sand_Prairie_and_Oak_Savanna.jpg',
    license: 'Wikimedia Commons listed license; verify exact reuse terms before publishing',
    retrieved: '2026-08-10',
    originalSourceId: 'src-j1-ch2-4-ppt',
    lessonIds: ['j1-ch2-4-biomes-lesson-1', 'j1-ch2-4-biomes-lesson-2'],
    slideIds: ['j1-ch2-4-six-biomes', 'j1-ch2-4-grassland', 'j1-ch2-4-grassland-soil'],
    usage: 'Representative grassland image for biome comparison and rainfall distinction.',
  },
  'biomes-deciduous-autumn': {
    id: 'biomes-deciduous-autumn',
    title: 'Autumn deciduous forest',
    type: 'photo',
    origin: 'external-educational',
    localPath: '/science-lessons/biomes/deciduous-autumn.jpg',
    alt: 'Aerial view of autumn colors in a deciduous forest',
    attribution: 'Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Aerial_View_of_Autumn_Forest_Colors.jpg',
    license: 'Wikimedia Commons listed license; verify exact reuse terms before publishing',
    retrieved: '2026-08-10',
    originalSourceId: 'src-j1-ch2-4-ppt',
    lessonIds: ['j1-ch2-4-biomes-lesson-1', 'j1-ch2-4-biomes-lesson-2'],
    slideIds: ['j1-ch2-4-deciduous-forest', 'j1-ch2-4-deciduous-climate'],
    usage: 'Shows seasonal leaf colour change for deciduous forest note-taking.',
  },
  'biomes-boreal-taiga': {
    id: 'biomes-boreal-taiga',
    title: 'Taiga coniferous forest',
    type: 'photo',
    origin: 'external-educational',
    localPath: '/science-lessons/biomes/boreal-taiga.jpg',
    alt: 'Taiga landscape with coniferous forest and lake',
    attribution: 'Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Taiga_Landscape_in_Canada.jpg',
    license: 'Wikimedia Commons listed license; verify exact reuse terms before publishing',
    retrieved: '2026-08-10',
    originalSourceId: 'src-j1-ch2-4-ppt',
    lessonIds: ['j1-ch2-4-biomes-lesson-1', 'j1-ch2-4-biomes-lesson-2'],
    slideIds: ['j1-ch2-4-boreal-forest', 'j1-ch2-4-boreal-animals'],
    usage: 'Shows coniferous tree dominance in boreal forest.',
  },
  'biomes-tundra-alpine': {
    id: 'biomes-tundra-alpine',
    title: 'Tundra landscape',
    type: 'photo',
    origin: 'external-educational',
    localPath: '/science-lessons/biomes/tundra-alpine.jpg',
    alt: 'Tundra landscape with low vegetation and open sky',
    attribution: 'Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tundra_(1).jpg',
    license: 'Wikimedia Commons listed license; verify exact reuse terms before publishing',
    retrieved: '2026-08-10',
    originalSourceId: 'src-j1-ch2-4-ppt',
    lessonIds: ['j1-ch2-4-biomes-lesson-1', 'j1-ch2-4-biomes-lesson-2'],
    slideIds: ['j1-ch2-4-tundra', 'j1-ch2-4-tundra-plants', 'j1-ch2-4-tundra-animals'],
    usage: 'Shows low vegetation and open cold landscape before the permafrost cross-section.',
  },
  'biomes-mountains-ice': {
    id: 'biomes-mountains-ice',
    title: 'Mountain glacier ice',
    type: 'photo',
    origin: 'external-educational',
    localPath: '/science-lessons/biomes/mountains-ice.jpg',
    alt: 'Mountain range and glacier ice near Juneau',
    attribution: 'Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:A_Juneau_Glacier_WM_gf41.jpg',
    license: 'Wikimedia Commons listed license; verify exact reuse terms before publishing',
    retrieved: '2026-08-10',
    originalSourceId: 'src-j1-ch2-4-ppt',
    lessonIds: ['j1-ch2-4-biomes-lesson-1', 'j1-ch2-4-biomes-lesson-2'],
    slideIds: ['j1-ch2-4-mountains-ice'],
    usage: 'Supports source idea that mountains and ice-covered land sit outside the six major biome list.',
  },
  'biomes-permafrost-pattern': {
    id: 'biomes-permafrost-pattern',
    title: 'Permafrost patterned ground',
    type: 'photo',
    origin: 'external-educational',
    localPath: '/science-lessons/biomes/permafrost-pattern.jpg',
    alt: 'Patterned ground caused by freeze-thaw processes in permafrost terrain',
    attribution: 'Wikimedia Commons',
    license: 'Wikimedia Commons listed license; verify exact reuse terms before publishing',
    retrieved: '2026-08-10',
    originalSourceId: 'src-j1-ch2-4-ppt',
    lessonIds: ['j1-ch2-4-biomes-lesson-1', 'j1-ch2-4-biomes-lesson-2'],
    slideIds: ['j1-ch2-4-tundra'],
    usage: 'Secondary texture/reference for tundra; cross-section diagram now carries the teaching explanation.',
    notes: 'Keep as supporting context, not the main permafrost explanation.',
  },
}

export const biomeAssetIds: Record<LessonBiomeKey, string> = {
  rainforest: 'biomes-rainforest-canopy',
  desert: 'biomes-desert-sahara',
  grassland: 'biomes-grassland-savanna',
  deciduous: 'biomes-deciduous-autumn',
  boreal: 'biomes-boreal-taiga',
  tundra: 'biomes-tundra-alpine',
  mountains: 'biomes-mountains-ice',
}

export const scienceVisualAssets: LessonVisualAsset[] = Object.values(biomesVisualAssets)

export function findVisualAsset(assetId: string | undefined) {
  return assetId ? biomesVisualAssets[assetId] : undefined
}
