import type { LessonSlide, ScienceLesson } from '../../types/lesson'

const driveUrl = (id: string) => `https://drive.google.com/file/d/${id}/view`

const sourceReferences = [
  {
    id: 'src-j1-ch2-4-ppt',
    type: 'presentation' as const,
    title: 'Copy of J1 PPT.pptx',
    location: 'Google Drive / J1Science',
    driveFileId: '1STwllX6-z931Hsqst_A1FvN7xwLCVI0g',
    url: 'https://docs.google.com/presentation/d/1STwllX6-z931Hsqst_A1FvN7xwLCVI0g/edit',
    slideRange: 'Chapter 2: Section 4, from "BIOMES" through "MOUNTAINS AND ICE"',
    notes: 'Authoritative source for the rebuilt teaching sequence. Embedded PPT images were not materialized into the repo in this checkpoint.',
  },
  {
    id: 'src-j1-ch2-4-notes',
    type: 'document' as const,
    title: '2026_03_10_biomes_student_notes.pdf',
    location: 'Google Drive / J1Science',
    driveFileId: '1gllgvUd9IiWh8UzJoZvSGxaj2bgRvcyy',
    url: driveUrl('1gllgvUd9IiWh8UzJoZvSGxaj2bgRvcyy'),
    notes: 'Used to cross-check the Ch.2.4 biome definitions and examples.',
  },
]

const slides: LessonSlide[] = [
  {
    id: 'j1-ch2-4-title',
    title: { en: 'Chapter 2.4: Biomes', zhHant: '第 2.4 章：生物群系' },
    body: {
      en: 'Today we connect climate to the major land ecosystems found on Earth.',
      zhHant: '今天我們會把氣候與地球上的主要陸地生態系連結起來。',
    },
    visual: 'ecosystem',
    layout: 'hero',
    emphasis: 'Climate shapes life',
    media: {
      type: 'image',
      title: 'Blue Marble world map',
      assetId: 'biomes-blue-marble',
      src: '/science-lessons/biomes/earth-blue-marble.jpg',
      alt: 'NASA Blue Marble world map showing global land, ocean, ice, and vegetation patterns',
      credit: 'NASA / Wikimedia Commons',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'title-1', text: { en: 'Key question: What factors determine the type of biome found in an area?', zhHant: '核心問題：哪些因素決定一個地區的生物群系？' } },
      { id: 'title-2', text: { en: 'Second question: What are the six major biomes found on Earth?', zhHant: '第二個問題：地球上六大主要生物群系是什麼？' } },
    ],
    teacherNote: 'Open by asking students to predict why Taiwan does not look like a desert or tundra. Keep English as the source language and use Chinese support for key terms.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-biome-definition',
    title: { en: 'What is a biome?', zhHant: '什麼是生物群系？' },
    body: {
      en: 'A biome is a group of land ecosystems with similar climates and organisms.',
      zhHant: '生物群系是一組具有相似氣候和生物的陸地生態系。',
    },
    visual: 'ecosystem',
    layout: 'concept',
    emphasis: 'climate + organisms',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'definition-1', text: { en: 'Similar climate', zhHant: '相似的氣候' } },
      { id: 'definition-2', text: { en: 'Similar organisms', zhHant: '相似的生物' } },
      { id: 'definition-3', text: { en: 'Climate means temperature + precipitation', zhHant: '氣候包含溫度和降水量' } },
    ],
    teacherNote: 'Do not rush the definition. Ask students to say which two climate parts they should listen for during every biome example.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-climate-drivers',
    title: { en: 'Climate determines the biome', zhHant: '氣候決定生物群系' },
    body: {
      en: 'To identify a biome, first ask how warm it is and how much precipitation falls there.',
      zhHant: '要判斷一個生物群系，先問那裡有多溫暖，以及有多少降水。',
    },
    visual: 'graph',
    layout: 'diagram',
    emphasis: 'temperature + precipitation',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'climate-1', text: { en: 'Temperature: hot, moderate, or cold?', zhHant: '溫度：炎熱、適中，還是寒冷？' } },
      { id: 'climate-2', text: { en: 'Precipitation: wet, seasonal, or dry?', zhHant: '降水：潮濕、季節性，還是乾燥？' } },
      { id: 'climate-3', text: { en: 'Organisms must survive those conditions.', zhHant: '生物必須能在那些條件下生存。' } },
    ],
    teacherNote: 'Frame the rest of the lesson as evidence gathering: every biome is a climate pattern plus organisms adapted to it.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-six-biomes',
    title: { en: 'Six major land biomes', zhHant: '六大主要陸地生物群系' },
    body: {
      en: 'The curriculum names six major biomes: rain forest, desert, grassland, deciduous forest, boreal forest, and tundra.',
      zhHant: '課程中的六大生物群系是：雨林、沙漠、草原、落葉林、北方針葉林和苔原。',
    },
    visual: 'ecosystem',
    layout: 'vocabulary',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'six-1', text: { en: 'Rain forest', zhHant: '雨林' } },
      { id: 'six-2', text: { en: 'Desert', zhHant: '沙漠' } },
      { id: 'six-3', text: { en: 'Grassland', zhHant: '草原' } },
      { id: 'six-4', text: { en: 'Deciduous forest', zhHant: '落葉林' } },
      { id: 'six-5', text: { en: 'Boreal forest', zhHant: '北方針葉林' } },
      { id: 'six-6', text: { en: 'Tundra', zhHant: '苔原' } },
    ],
    teacherNote: 'Use the reveals as a quick call-and-repeat vocabulary moment. Students will need these names for the homework and quiz.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-rain-forest',
    title: { en: 'Rain forest biomes', zhHant: '雨林生物群系' },
    body: {
      en: 'Temperate rain forests have moderate temperatures and receive a lot of rain. Tropical rain forests are warm and humid all year.',
      zhHant: '溫帶雨林氣溫適中且降雨量多；熱帶雨林全年溫暖潮濕。',
    },
    visual: 'ecosystem',
    layout: 'image-focus',
    biomeKey: 'rainforest',
    emphasis: 'warm + wet',
    media: {
      type: 'image',
      title: 'Rainforest canopy near Cairns',
      assetId: 'biomes-rainforest-canopy',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'rain-1', text: { en: 'Temperate rain forests: moderate temperatures, about 300 cm rain per year', zhHant: '溫帶雨林：氣溫適中，每年約 300 公分降雨' } },
      { id: 'rain-2', text: { en: 'Tropical rain forests: warm and humid all year', zhHant: '熱帶雨林：全年溫暖潮濕' } },
      { id: 'rain-3', text: { en: 'Canopy: leafy roof formed by tall trees', zhHant: '樹冠層：高大樹木形成的 leafy roof' } },
      { id: 'rain-4', text: { en: 'Understory: shorter trees and vines growing in shade', zhHant: '下層林：在陰影中生長的較矮樹木和藤蔓' } },
    ],
    teacherNote: 'Preserve the canopy/understory distinction from the source. Ask students to gesture high/low as each layer appears.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-desert',
    title: { en: 'Desert biomes', zhHant: '沙漠生物群系' },
    body: {
      en: 'A desert receives less than 25 centimeters of rain per year. Evaporation is greater than precipitation.',
      zhHant: '沙漠每年降雨少於 25 公分，蒸發量大於降水量。',
    },
    visual: 'graph',
    layout: 'diagram',
    biomeKey: 'desert',
    emphasis: '< 25 cm rain/year',
    media: {
      type: 'image',
      title: 'Sahara desert dunes',
      assetId: 'biomes-desert-sahara',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'desert-1', text: { en: 'Rainfall: less than 25 cm per year', zhHant: '降雨：每年少於 25 公分' } },
      { id: 'desert-2', text: { en: 'Evaporation > precipitation', zhHant: '蒸發量大於降水量' } },
      { id: 'desert-3', text: { en: 'Many deserts cool rapidly after sunset', zhHant: '許多沙漠在日落後迅速降溫' } },
      { id: 'desert-4', text: { en: 'Many animals are active at night', zhHant: '許多動物在夜間活動' } },
    ],
    teacherNote: 'The comparison symbol is the key teaching move. Have students explain why night activity helps animals survive.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-grassland',
    title: { en: 'Grassland biomes', zhHant: '草原生物群系' },
    body: {
      en: 'Grasslands are populated mostly by grasses and other non-woody plants. Prairies and savannas differ in rainfall.',
      zhHant: '草原主要由草和其他非木本植物組成；大草原和稀樹草原的差別在於年降雨量。',
    },
    visual: 'ecosystem',
    layout: 'comparison',
    biomeKey: 'grassland',
    emphasis: 'grasses, not forests',
    media: {
      type: 'image',
      title: 'Sand prairie and oak savanna',
      assetId: 'biomes-grassland-savanna',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'grass-1', text: { en: 'Savannas: about 120 cm rain per year', zhHant: '稀樹草原：每年約 120 公分降雨' } },
      { id: 'grass-2', text: { en: 'Prairies: about 25-75 cm rain per year', zhHant: '大草原：每年約 25-75 公分降雨' } },
      { id: 'grass-3', text: { en: 'Rich soil supports tall grasses', zhHant: '肥沃土壤支持高草生長' } },
      { id: 'grass-4', text: { en: 'Not enough rain for very big trees', zhHant: '降雨不足以支持非常高大的樹木' } },
    ],
    teacherNote: 'This slide is a good place to ask students to compare grassland and desert using precipitation numbers.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-deciduous-forest',
    title: { en: 'Deciduous forest biomes', zhHant: '落葉林生物群系' },
    body: {
      en: 'Deciduous trees shed their leaves and grow new ones each year. Oaks and maples are examples.',
      zhHant: '落葉樹每年會落葉並長出新葉；橡樹和楓樹是例子。',
    },
    visual: 'particles',
    layout: 'image-focus',
    biomeKey: 'deciduous',
    emphasis: 'leaves change each year',
    media: {
      type: 'image',
      title: 'Autumn deciduous forest',
      assetId: 'biomes-deciduous-autumn',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'deciduous-1', text: { en: 'Deciduous trees lose leaves each year', zhHant: '落葉樹每年會落葉' } },
      { id: 'deciduous-2', text: { en: 'About 50 cm rain per year', zhHant: '每年約 50 公分降雨' } },
      { id: 'deciduous-3', text: { en: 'Temperatures vary greatly', zhHant: '氣溫變化很大' } },
      { id: 'deciduous-4', text: { en: 'Growing season usually lasts 5-6 months', zhHant: '生長季通常持續 5-6 個月' } },
    ],
    teacherNote: 'Connect directly to the quiz wording: students must recognize trees that lose leaves during a certain time of year.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-boreal-forest',
    title: { en: 'Boreal forest biomes', zhHant: '北方針葉林生物群系' },
    body: {
      en: 'Most boreal forest trees are coniferous: they produce seeds in cones and have needle-shaped leaves.',
      zhHant: '北方針葉林多為針葉樹：種子在毬果中形成，葉子像針。',
    },
    visual: 'ecosystem',
    layout: 'image-focus',
    biomeKey: 'boreal',
    emphasis: 'cones + needles',
    media: {
      type: 'image',
      title: 'Taiga coniferous forest',
      assetId: 'biomes-boreal-taiga',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'boreal-1', text: { en: 'Coniferous trees', zhHant: '針葉樹' } },
      { id: 'boreal-2', text: { en: 'Seeds in cones', zhHant: '種子在毬果中' } },
      { id: 'boreal-3', text: { en: 'Needle-shaped leaves', zhHant: '針狀葉' } },
      { id: 'boreal-4', text: { en: 'Very cold winters; warm summers melt snow', zhHant: '冬天非常寒冷；夏天溫暖足以融雪' } },
      { id: 'boreal-5', text: { en: 'Animals include red squirrels, lynxes, wolves, insects, and birds', zhHant: '動物包括紅松鼠、猞猁、狼、昆蟲和鳥類' } },
    ],
    teacherNote: 'Keep plant traits first, then animal examples. The homework asks students to name boreal forest animals.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-tundra',
    title: { en: 'Tundra biomes', zhHant: '苔原生物群系' },
    body: {
      en: 'The tundra is extremely cold and dry. Most soil is frozen all year; the frozen soil is called permafrost.',
      zhHant: '苔原非常寒冷乾燥；多數土壤全年結冰，這種凍土稱為永久凍土。',
    },
    visual: 'question',
    layout: 'diagram',
    biomeKey: 'tundra',
    emphasis: 'permafrost',
    media: {
      type: 'image',
      title: 'Tundra landscape',
      assetId: 'biomes-tundra-alpine',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'tundra-1', text: { en: 'Extremely cold and dry', zhHant: '非常寒冷乾燥' } },
      { id: 'tundra-2', text: { en: 'May receive no more precipitation than deserts', zhHant: '降水量可能不比沙漠多' } },
      { id: 'tundra-3', text: { en: 'Permafrost: frozen soil', zhHant: '永久凍土：結冰的土壤' } },
      { id: 'tundra-4', text: { en: 'Summer rainwater cannot soak into permafrost, creating a marsh', zhHant: '夏季雨水無法滲入永久凍土，因此形成沼澤' } },
    ],
    teacherNote: 'Pause on permafrost. This exact vocabulary appears in the homework and quiz.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-mountains-ice',
    title: { en: 'Mountains and ice', zhHant: '山地與冰原' },
    body: {
      en: 'Some land areas are not part of any major biome, including mountain ranges and land covered in thick sheets of ice.',
      zhHant: '有些陸地區域不屬於任何主要生物群系，包括山脈和被厚冰層覆蓋的土地。',
    },
    visual: 'graph',
    layout: 'image-focus',
    biomeKey: 'mountains',
    emphasis: 'not one major biome',
    media: {
      type: 'image',
      title: 'Mountain glacier ice',
      assetId: 'biomes-mountains-ice',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'mountains-1', text: { en: 'Mountains are not one single major biome', zhHant: '山地不是單一主要生物群系' } },
      { id: 'mountains-2', text: { en: 'Ice-covered land is also outside the major biome list', zhHant: '被冰覆蓋的土地也不在主要生物群系列表中' } },
      { id: 'mountains-3', text: { en: 'As elevation changes, different biomes can appear', zhHant: '海拔改變時，可能出現不同的生物群系' } },
    ],
    teacherNote: 'Use this as a final concept check: ask why going up a mountain can feel like moving through different climates.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-rainfall-spectrum',
    title: { en: 'Rainfall changes the ecosystem', zhHant: '降雨量會改變生態系' },
    body: {
      en: 'From desert to rain forest, precipitation is one of the clearest clues for identifying a biome.',
      zhHant: '從沙漠到雨林，降水量是判斷生物群系最清楚的線索之一。',
    },
    visual: 'graph',
    layout: 'comparison',
    emphasis: 'less rain → more rain',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'spectrum-1', text: { en: 'Desert: less than 25 cm per year', zhHant: '沙漠：每年少於 25 公分' } },
      { id: 'spectrum-2', text: { en: 'Prairie: about 25-75 cm per year', zhHant: '大草原：約 25-75 公分' } },
      { id: 'spectrum-3', text: { en: 'Savanna: about 120 cm per year', zhHant: '稀樹草原：約 120 公分' } },
      { id: 'spectrum-4', text: { en: 'Temperate rain forest: about 300 cm per year', zhHant: '溫帶雨林：約 300 公分' } },
    ],
    teacherNote: 'Use this as retrieval before the exit check. Students should use the numbers as evidence, not as isolated facts.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-exit-check',
    title: { en: 'Exit check', zhHant: '課堂檢核' },
    body: {
      en: 'Use the biome evidence: climate, organisms, rainfall, temperature, and key adaptations.',
      zhHant: '使用生物群系證據：氣候、生物、降雨量、溫度和關鍵適應特徵。',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'prove it with evidence',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'exit-1', text: { en: 'Which two climate parts determine a biome?', zhHant: '哪兩個氣候部分決定生物群系？' } },
      { id: 'exit-2', text: { en: 'Name the six major biomes.', zhHant: '說出六大主要生物群系。' } },
      { id: 'exit-3', text: { en: 'What is permafrost?', zhHant: '什麼是永久凍土？' } },
      { id: 'exit-4', text: { en: 'Choose one biome and explain one survival condition.', zhHant: '選一個生物群系，說明一個生存條件。' } },
    ],
    teacherNote: 'These checks align with the homework, quiz, and student notes. Move into the worksheet only after students can answer verbally.',
    sourceId: 'src-j1-ch2-4-notes',
  },
]

export const j1Ch24BiomesLesson: ScienceLesson = {
  id: 'j1-ch2-4-biomes-real-pilot',
  unitId: 'j1-ch2-biomes',
  title: 'REAL PILOT: Ch.2.4 Biomes',
  subtitle: 'Climate factors and the six major land biomes',
  year: 'J1',
  semester: 'Fall',
  chapter: 'Ch.2.4',
  lessonOrder: 0,
  duration: 50,
  status: 'Published',
  updated: '10 August 2026',
  objectives: [
    'Define biome using climate and organisms.',
    'Identify temperature and precipitation as the climate factors that determine a biome.',
    'Name and distinguish the six major land biomes from the source curriculum.',
    'Use key evidence such as canopy, understory, rainfall, deciduous trees, coniferous trees, and permafrost.',
  ],
  sourceReferences,
  slides,
  resources: [
    {
      id: 'j1-ch2-4-ppt-source',
      title: 'Source PPT: Copy of J1 PPT.pptx',
      type: 'Presentation',
      format: 'PPTX',
      detail: 'Drive source · Ch.2.4 section',
      href: 'https://docs.google.com/presentation/d/1STwllX6-z931Hsqst_A1FvN7xwLCVI0g/edit',
      driveFileId: '1STwllX6-z931Hsqst_A1FvN7xwLCVI0g',
      sourceId: 'src-j1-ch2-4-ppt',
      teacherOnly: true,
    },
    {
      id: 'j1-ch2-4-homework',
      title: 'J1 Sci Ch.2.4 HW',
      type: 'Worksheet',
      format: 'PDF',
      detail: 'Homework PDF · 10 questions',
      href: driveUrl('1ANbOTp6a4V32oOsAxH2MdRUcE_B_RGEb'),
      driveFileId: '1ANbOTp6a4V32oOsAxH2MdRUcE_B_RGEb',
    },
    {
      id: 'j1-ch2-4-quiz',
      title: 'J1 Sci Ch.2.4 Quiz',
      type: 'Quiz',
      format: 'PDF',
      detail: 'Quiz PDF · 10 questions',
      href: driveUrl('1im18Xue1lG6hbOdsdOZW9n-MiihkSczd'),
      driveFileId: '1im18Xue1lG6hbOdsdOZW9n-MiihkSczd',
    },
    {
      id: 'j1-ch2-4-student-notes',
      title: 'Biomes student notes',
      type: 'Classwork',
      format: 'PDF',
      detail: 'Student notes PDF · 2 pages',
      href: driveUrl('1gllgvUd9IiWh8UzJoZvSGxaj2bgRvcyy'),
      driveFileId: '1gllgvUd9IiWh8UzJoZvSGxaj2bgRvcyy',
      sourceId: 'src-j1-ch2-4-notes',
    },
  ],
}
