import type { LessonSlide, ScienceLesson } from '../../types/lesson'

const driveUrl = (id: string) => `https://drive.google.com/file/d/${id}/view`

const sourceReferences = [
  {
    id: 'src-j1-ch2-4-ppt',
    type: 'presentation' as const,
    title: 'Copy of J1 PPT.pptx',
    location: 'Google Drive / J1Science',
    driveFileId: '1STwllX6-z931Hsqst_A1FvN7xwLCVI0g',
    url: 'https://docs.google.com/presentation/d/1STwllX6-z931Hsqst_A1FvN7xwLCVI0g/edit',
    slideRange: 'Slides 99-116, Chapter 2 Section 4 Biomes',
    notes: 'Authoritative PowerPoint source. Local extraction verified slides 99-116 as Biomes and slide 117 as Chapter 2 Section 5.',
  },
  {
    id: 'src-j1-ch2-4-notes',
    type: 'document' as const,
    title: '2026_03_10_biomes_student_notes.pdf',
    location: 'Google Drive / J1Science',
    driveFileId: '1gllgvUd9IiWh8UzJoZvSGxaj2bgRvcyy',
    url: driveUrl('1gllgvUd9IiWh8UzJoZvSGxaj2bgRvcyy'),
    notes: 'Authoritative two-page student notes for Ch.2.4 Biomes.',
  },
  {
    id: 'src-j1-ch2-4-homework',
    type: 'worksheet' as const,
    title: 'J1 Sci Ch.2.4 HW.pdf',
    location: 'Google Drive / J1Science',
    driveFileId: '1ANbOTp6a4V32oOsAxH2MdRUcE_B_RGEb',
    url: driveUrl('1ANbOTp6a4V32oOsAxH2MdRUcE_B_RGEb'),
    notes: 'Authoritative 10-question homework aligned to the Biomes unit.',
  },
  {
    id: 'src-j1-ch2-4-quiz',
    type: 'quiz' as const,
    title: 'J1 Sci Ch.2.4 Quiz.pdf',
    location: 'Google Drive / J1Science',
    driveFileId: '1im18Xue1lG6hbOdsdOZW9n-MiihkSczd',
    url: driveUrl('1im18Xue1lG6hbOdsdOZW9n-MiihkSczd'),
    notes: 'Authoritative 10-question quiz aligned to the Biomes unit.',
  },
]

const sharedResources = [
  {
    id: 'j1-ch2-4-ppt-source',
    title: 'Source PPT: Copy of J1 PPT.pptx',
    type: 'Presentation' as const,
    format: 'PPTX' as const,
    detail: 'Drive source - slides 99-116',
    href: 'https://docs.google.com/presentation/d/1STwllX6-z931Hsqst_A1FvN7xwLCVI0g/edit',
    driveFileId: '1STwllX6-z931Hsqst_A1FvN7xwLCVI0g',
    sourceId: 'src-j1-ch2-4-ppt',
    teacherOnly: true,
  },
  {
    id: 'j1-ch2-4-student-notes',
    title: 'Biomes student notes',
    type: 'Classwork' as const,
    format: 'PDF' as const,
    detail: 'Student notes PDF - 2 pages',
    href: driveUrl('1gllgvUd9IiWh8UzJoZvSGxaj2bgRvcyy'),
    driveFileId: '1gllgvUd9IiWh8UzJoZvSGxaj2bgRvcyy',
    sourceId: 'src-j1-ch2-4-notes',
  },
  {
    id: 'j1-ch2-4-homework',
    title: 'J1 Sci Ch.2.4 HW',
    type: 'Worksheet' as const,
    format: 'PDF' as const,
    detail: 'Homework PDF - 10 questions',
    href: driveUrl('1ANbOTp6a4V32oOsAxH2MdRUcE_B_RGEb'),
    driveFileId: '1ANbOTp6a4V32oOsAxH2MdRUcE_B_RGEb',
    sourceId: 'src-j1-ch2-4-homework',
  },
  {
    id: 'j1-ch2-4-quiz',
    title: 'J1 Sci Ch.2.4 Quiz',
    type: 'Quiz' as const,
    format: 'PDF' as const,
    detail: 'Quiz PDF - 10 questions',
    href: driveUrl('1im18Xue1lG6hbOdsdOZW9n-MiihkSczd'),
    driveFileId: '1im18Xue1lG6hbOdsdOZW9n-MiihkSczd',
    sourceId: 'src-j1-ch2-4-quiz',
  },
]

const lesson1Slides: LessonSlide[] = [
  {
    id: 'j1-ch2-4-title',
    title: { en: 'Chapter 2.4: Biomes', zhHant: '第 2.4 章：生物群系' },
    body: {
      en: 'Today we begin Chapter 2 Section 4 and connect climate to the major land ecosystems found on Earth.',
      zhHant: '今天開始第 2 章第 4 節，連結氣候與地球上的主要陸地生態系。',
    },
    visual: 'ecosystem',
    layout: 'hero',
    emphasis: 'Source PPT slide 99',
    media: {
      type: 'image',
      title: 'Blue Marble world map',
      assetId: 'biomes-blue-marble',
      src: '/science-lessons/biomes/earth-blue-marble.jpg',
      alt: 'NASA Blue Marble world map showing global land, ocean, ice, and vegetation patterns',
      credit: 'NASA / Wikimedia Commons',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'title-1', text: { en: 'Chapter 2: Section 4', zhHant: '第 2 章：第 4 節' } },
      { id: 'title-2', text: { en: 'Biomes are large patterns of climate and life.', zhHant: '生物群系是氣候與生命的大型模式。' } },
    ],
    teacherNote: 'Open from the source title slide. Keep the focus on the chapter transition and tell students they will use climate evidence to identify biomes.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-question-day-factors',
    title: { en: 'Question of the Day', zhHant: '今日問題' },
    body: {
      en: 'What factors determine the type of biome found in an area?',
      zhHant: '哪些因素決定一個地區會出現哪一種生物群系？',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'factors determine biome',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'qod-factors-1', text: { en: 'Listen for two climate parts.', zhHant: '留意兩個氣候部分。' } },
      { id: 'qod-factors-2', text: { en: 'Use evidence, not guesses.', zhHant: '使用證據，不只是猜測。' } },
    ],
    teacherNote: 'Source slide 100. Let students predict before giving the definition. Collect temperature and precipitation if they offer them.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-biome-definition',
    title: { en: 'What is a biome?', zhHant: '什麼是生物群系？' },
    body: {
      en: 'A biome is a group of land ecosystems with similar climates and organisms.',
      zhHant: '生物群系是一組具有相似氣候和生物的陸地生態系。',
    },
    visual: 'ecosystem',
    layout: 'concept',
    emphasis: 'climate + organisms',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'definition-1', text: { en: 'Similar climate', zhHant: '相似的氣候' } },
      { id: 'definition-2', text: { en: 'Similar organisms', zhHant: '相似的生物' } },
      { id: 'definition-3', text: { en: 'Climate means temperature + precipitation', zhHant: '氣候包含溫度和降水量' } },
    ],
    teacherNote: 'Source slide 101 and student notes p.1. This is the anchor definition for homework question 1 and climate question 3.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-climate-drivers',
    title: { en: 'Climate determines the biome', zhHant: '氣候決定生物群系' },
    body: {
      en: 'The climate in an area, especially temperature and precipitation, determines its biome.',
      zhHant: '一個地區的氣候，特別是溫度和降水量，會決定它的生物群系。',
    },
    visual: 'graph',
    layout: 'diagram',
    emphasis: 'temperature + precipitation',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'climate-1', text: { en: 'Temperature: how hot or cold?', zhHant: '溫度：有多熱或多冷？' } },
      { id: 'climate-2', text: { en: 'Precipitation: how much rain or snow?', zhHant: '降水量：有多少雨或雪？' } },
      { id: 'climate-3', text: { en: 'Organisms must survive those conditions.', zhHant: '生物必須能在那些條件下生存。' } },
    ],
    teacherNote: 'Generated from source slide 101 wording. Use the V2 diagram to make the two climate factors explicit before the examples.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-six-biomes',
    title: { en: 'Six major land biomes', zhHant: '六大主要陸地生物群系' },
    body: {
      en: 'The source names six major biomes: rain forest, desert, grassland, deciduous forest, boreal forest, and tundra.',
      zhHant: '原始教材列出六大主要生物群系：雨林、沙漠、草原、落葉林、北方針葉林和苔原。',
    },
    visual: 'ecosystem',
    layout: 'vocabulary',
    media: {
      type: 'image',
      title: 'Sand prairie and oak savanna',
      assetId: 'biomes-grassland-savanna',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'six-1', text: { en: 'Rain forest', zhHant: '雨林 rain forest' } },
      { id: 'six-2', text: { en: 'Desert', zhHant: '沙漠 desert' } },
      { id: 'six-3', text: { en: 'Grassland', zhHant: '草原 grassland' } },
      { id: 'six-4', text: { en: 'Deciduous forest', zhHant: '落葉林 deciduous forest' } },
      { id: 'six-5', text: { en: 'Boreal forest', zhHant: '北方針葉林 boreal forest' } },
      { id: 'six-6', text: { en: 'Tundra', zhHant: '苔原 tundra' } },
    ],
    teacherNote: 'Source slides 101-102. Use this to prepare homework question 2 and quiz word-bank recognition.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-rain-forest',
    title: { en: 'Rain forest biomes', zhHant: '雨林生物群系' },
    body: {
      en: 'Temperate rain forests have moderate temperatures and about 300 cm of rain per year. Tropical rain forests are warm and humid all year long.',
      zhHant: '溫帶雨林氣溫適中，每年約有 300 公分降雨。熱帶雨林全年溫暖潮濕。',
    },
    visual: 'ecosystem',
    layout: 'image-focus',
    biomeKey: 'rainforest',
    emphasis: 'warm or moderate + lots of rain',
    media: {
      type: 'image',
      title: 'Rainforest canopy near Cairns',
      assetId: 'biomes-rainforest-canopy',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'rain-1', text: { en: 'Temperate rain forest: moderate temperatures, lots of rain', zhHant: '溫帶雨林：氣溫適中，降雨很多' } },
      { id: 'rain-2', text: { en: 'About 300 centimeters of rain per year', zhHant: '每年約 300 公分降雨' } },
      { id: 'rain-3', text: { en: 'Tropical rain forest: warm and humid all year long', zhHant: '熱帶雨林：全年溫暖潮濕' } },
    ],
    teacherNote: 'Source slide 103. Separate temperate and tropical rain forests clearly because homework question 4 and quiz question 5 assess this distinction.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-rainforest-layers',
    title: { en: 'Canopy and understory', zhHant: '樹冠層與林下層' },
    body: {
      en: 'Tall trees form a leafy roof called the canopy. Shorter trees and vines form an understory that grows well in the shade.',
      zhHant: '高大的樹形成像葉子屋頂的樹冠層。較矮的樹和藤蔓形成在陰影中生長良好的林下層。',
    },
    visual: 'ecosystem',
    layout: 'diagram',
    biomeKey: 'rainforest',
    emphasis: 'canopy over understory',
    media: {
      type: 'image',
      title: 'Rainforest canopy near Cairns',
      assetId: 'biomes-rainforest-canopy',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'layers-1', text: { en: 'Canopy: leafy roof made by tall trees', zhHant: '樹冠層 canopy：高大樹木形成的葉子屋頂' } },
      { id: 'layers-2', text: { en: 'Understory: shorter trees and vines in the shade', zhHant: '林下層 understory：陰影中的較矮樹木與藤蔓' } },
      { id: 'layers-3', text: { en: 'Rain forests provide good habitat for many species.', zhHant: '雨林為許多物種提供良好的棲地。' } },
    ],
    teacherNote: 'Source slide 104. Have students point high and low as you reveal canopy and understory. This directly prepares homework question 5 and quiz questions 3-4.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-desert',
    title: { en: 'Desert biomes', zhHant: '沙漠生物群系' },
    body: {
      en: 'A desert receives less than 25 centimeters of rain per year. Evaporation is greater than precipitation.',
      zhHant: '沙漠每年降雨少於 25 公分，而且蒸發量大於降水量。',
    },
    visual: 'graph',
    layout: 'diagram',
    biomeKey: 'desert',
    emphasis: '< 25 cm rain/year',
    media: {
      type: 'image',
      title: 'Sahara desert dunes',
      assetId: 'biomes-desert-sahara',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'desert-1', text: { en: 'Rainfall: less than 25 cm per year', zhHant: '降雨：每年少於 25 公分' } },
      { id: 'desert-2', text: { en: 'Evaporation > precipitation', zhHant: '蒸發量大於降水量' } },
      { id: 'desert-3', text: { en: 'Extreme heat helps drive water loss.', zhHant: '極端炎熱會增加水分流失。' } },
    ],
    teacherNote: 'Source slide 105. Keep the comparison symbol central. Students need this for homework question 6 and for contrasting desert with tundra.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-desert-night',
    title: { en: 'Desert nights', zhHant: '沙漠夜晚' },
    body: {
      en: 'Many deserts cool down rapidly after sunset. Many animals are active at night when temperatures are cooler.',
      zhHant: '許多沙漠在日落後會快速降溫。許多動物會在較涼爽的夜晚活動。',
    },
    visual: 'ecosystem',
    layout: 'image-focus',
    biomeKey: 'desert',
    emphasis: 'cooler nights support activity',
    media: {
      type: 'image',
      title: 'Sahara desert dunes',
      assetId: 'biomes-desert-sahara',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'desert-night-1', text: { en: 'Deserts cool rapidly when the sun goes down.', zhHant: '太陽下山後，沙漠會快速降溫。' } },
      { id: 'desert-night-2', text: { en: 'Nocturnal animals avoid the hottest part of the day.', zhHant: '夜行性動物避開一天中最熱的時間。' } },
    ],
    teacherNote: 'Source slide 106. Ask students why being active at night helps an animal survive in a desert.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-grassland',
    title: { en: 'Grassland biomes', zhHant: '草原生物群系' },
    body: {
      en: 'Grasslands are populated mostly by grasses and other non-woody plants. They are either prairies or savannas.',
      zhHant: '草原主要由草和其他非木本植物組成。草原可以是大草原或稀樹草原。',
    },
    visual: 'ecosystem',
    layout: 'comparison',
    biomeKey: 'grassland',
    emphasis: 'prairie and savanna',
    media: {
      type: 'image',
      title: 'Sand prairie and oak savanna',
      assetId: 'biomes-grassland-savanna',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'grass-1', text: { en: 'Prairie: 25-75 cm of rain per year', zhHant: '大草原 prairie：每年 25-75 公分降雨' } },
      { id: 'grass-2', text: { en: 'Savanna: 120 cm of rain per year', zhHant: '稀樹草原 savanna：每年 120 公分降雨' } },
      { id: 'grass-3', text: { en: 'Rainfall differences separate the two grassland types.', zhHant: '降雨量差異區分這兩種草原。' } },
    ],
    teacherNote: 'Source slide 107. Use the prairie/savanna contrast for homework question 7 and quiz question 10.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-grassland-soil',
    title: { en: 'Grassland vegetation and soil', zhHant: '草原植被與土壤' },
    body: {
      en: 'Grasslands have more comfortable temperatures than deserts. Rich soil supports tall grasses, but there is not enough rain for very big trees.',
      zhHant: '草原的溫度比沙漠舒適。肥沃土壤支持高草生長，但降雨不足以支持非常高大的樹木。',
    },
    visual: 'ecosystem',
    layout: 'image-focus',
    biomeKey: 'grassland',
    emphasis: 'rich soil, limited trees',
    media: {
      type: 'image',
      title: 'Sand prairie and oak savanna',
      assetId: 'biomes-grassland-savanna',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'grass-soil-1', text: { en: 'Rich soil supports tall grasses.', zhHant: '肥沃土壤支持高草生長。' } },
      { id: 'grass-soil-2', text: { en: 'Rainfall is not enough for very big trees.', zhHant: '降雨不足以支持非常高大的樹木。' } },
      { id: 'grass-soil-3', text: { en: 'Check: Which grassland gets 120 cm of rain?', zhHant: '檢核：哪一種草原每年有 120 公分降雨？' } },
    ],
    teacherNote: 'Source slide 108. This is the lesson 1 consolidation slide. Ask students to answer savanna, then contrast with prairie.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
]

const lesson2Slides: LessonSlide[] = [
  {
    id: 'j1-ch2-4-deciduous-forest',
    title: { en: 'Deciduous forest biomes', zhHant: '落葉林生物群系' },
    body: {
      en: 'Many trees in this forest are deciduous trees: they shed their leaves and grow new ones each year.',
      zhHant: '這種森林中許多樹是落葉樹：它們每年落葉並長出新葉。',
    },
    visual: 'particles',
    layout: 'image-focus',
    biomeKey: 'deciduous',
    emphasis: 'shed leaves, grow new ones',
    media: {
      type: 'image',
      title: 'Autumn deciduous forest',
      assetId: 'biomes-deciduous-autumn',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'deciduous-1', text: { en: 'Deciduous = shed leaves and grow new ones each year', zhHant: '落葉 deciduous：每年落葉並長出新葉' } },
      { id: 'deciduous-2', text: { en: 'Oaks and maples are deciduous trees.', zhHant: '橡樹和楓樹是落葉樹。' } },
      { id: 'deciduous-3', text: { en: 'Quiz clue: trees lose leaves during a certain time of year.', zhHant: '測驗線索：樹在一年中的某段時間落葉。' } },
    ],
    teacherNote: 'Source slide 109. Start lesson 2 by retrieving the six-biome list, then anchor the meaning of deciduous for homework question 8 and quiz question 8.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-deciduous-climate',
    title: { en: 'Deciduous forest climate', zhHant: '落葉林氣候' },
    body: {
      en: 'Deciduous forests receive enough rain for trees, about 50 cm per year. Temperatures vary greatly and the growing season usually lasts 5-6 months.',
      zhHant: '落葉林有足夠雨量支持樹木生長，每年約 50 公分。氣溫變化很大，生長季通常持續 5-6 個月。',
    },
    visual: 'ecosystem',
    layout: 'comparison',
    biomeKey: 'deciduous',
    emphasis: 'rain + seasonal change',
    media: {
      type: 'image',
      title: 'Autumn deciduous forest',
      assetId: 'biomes-deciduous-autumn',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'deciduous-climate-1', text: { en: 'Enough rain supports trees and other plants.', zhHant: '足夠雨量支持樹木和其他植物生長。' } },
      { id: 'deciduous-climate-2', text: { en: 'About 50 cm of rain per year', zhHant: '每年約 50 公分降雨' } },
      { id: 'deciduous-climate-3', text: { en: 'Growing season: usually 5-6 months', zhHant: '生長季：通常 5-6 個月' } },
      { id: 'deciduous-climate-4', text: { en: 'Animals include bears, deer, red foxes, and birds.', zhHant: '動物包括熊、鹿、赤狐和鳥類。' } },
    ],
    teacherNote: 'Source slide 110. Keep rainfall, seasonal temperature change, growing season, and animals together as the assessed deciduous forest evidence.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-boreal-forest',
    title: { en: 'Boreal forest plants', zhHant: '北方針葉林植物' },
    body: {
      en: 'Most boreal forest trees are coniferous trees. They produce seeds in cones and have leaves shaped like needles.',
      zhHant: '北方針葉林中的大多數樹是針葉樹。它們在毬果中產生種子，葉子像針一樣。',
    },
    visual: 'ecosystem',
    layout: 'image-focus',
    biomeKey: 'boreal',
    emphasis: 'cones + needles',
    media: {
      type: 'image',
      title: 'Taiga coniferous forest',
      assetId: 'biomes-boreal-taiga',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'boreal-1', text: { en: 'Coniferous trees', zhHant: '針葉樹 coniferous trees' } },
      { id: 'boreal-2', text: { en: 'Seeds in cones', zhHant: '種子在毬果 cones 中' } },
      { id: 'boreal-3', text: { en: 'Leaves shaped like needles', zhHant: '葉子呈針狀 needle-shaped leaves' } },
      { id: 'boreal-4', text: { en: 'Very cold winters; summers warm enough to melt snow', zhHant: '冬天非常寒冷；夏天溫暖到足以融雪' } },
    ],
    teacherNote: 'Source slide 111. Keep plant traits first, then climate. This prepares students to distinguish boreal forest from deciduous forest.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-boreal-animals',
    title: { en: 'Boreal forest animals', zhHant: '北方針葉林動物' },
    body: {
      en: 'Animals eat the seeds of coniferous trees. Red squirrels, lynxes, wolves, insects, and birds enjoy this forest.',
      zhHant: '動物會吃針葉樹的種子。紅松鼠、猞猁、狼、昆蟲和鳥類生活在這種森林中。',
    },
    visual: 'ecosystem',
    layout: 'image-focus',
    biomeKey: 'boreal',
    emphasis: 'herbivores and carnivores',
    media: {
      type: 'image',
      title: 'Taiga coniferous forest',
      assetId: 'biomes-boreal-taiga',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'boreal-animals-1', text: { en: 'Some animals eat conifer seeds.', zhHant: '有些動物吃針葉樹種子。' } },
      { id: 'boreal-animals-2', text: { en: 'Examples: red squirrels, lynxes, wolves, insects, birds', zhHant: '例子：紅松鼠、猞猁、狼、昆蟲、鳥類' } },
      { id: 'boreal-animals-3', text: { en: 'There are herbivores and carnivores.', zhHant: '這裡有草食動物和肉食動物。' } },
    ],
    teacherNote: 'Source slide 112. Homework question 9 asks for three boreal forest animals, so pause for students to record at least three examples.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-tundra',
    title: { en: 'Tundra biomes', zhHant: '苔原生物群系' },
    body: {
      en: 'The tundra is extremely cold and dry. It may receive no more precipitation than deserts, and most soil is frozen all year.',
      zhHant: '苔原非常寒冷乾燥。它的降水量可能不比沙漠多，而且大多數土壤全年結冰。',
    },
    visual: 'question',
    layout: 'diagram',
    biomeKey: 'tundra',
    emphasis: 'permafrost',
    media: {
      type: 'image',
      title: 'Tundra landscape',
      assetId: 'biomes-tundra-alpine',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'tundra-1', text: { en: 'Extremely cold and dry', zhHant: '非常寒冷乾燥' } },
      { id: 'tundra-2', text: { en: 'May receive no more precipitation than deserts', zhHant: '降水量可能不比沙漠多' } },
      { id: 'tundra-3', text: { en: 'Permafrost = frozen soil', zhHant: '永久凍土 permafrost = 結冰的土壤' } },
      { id: 'tundra-4', text: { en: 'Summer rainwater cannot soak in, creating a marsh.', zhHant: '夏季雨水無法滲入，因此形成沼澤。' } },
    ],
    teacherNote: 'Source slide 113. Permafrost is tested directly in homework question 10 and quiz question 2. Also connect tundra to quiz question 1.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-tundra-plants',
    title: { en: 'Tundra plants and short summer', zhHant: '苔原植物與短暫夏季' },
    body: {
      en: 'Mosses, grasses, shrubs, and dwarf trees grow in the tundra. Most growth happens during the long days of the short summer season.',
      zhHant: '苔原中生長苔蘚、草、灌木和矮樹。大多數生長發生在短暫夏季的長日照期間。',
    },
    visual: 'ecosystem',
    layout: 'image-focus',
    biomeKey: 'tundra',
    emphasis: 'long days, short season',
    media: {
      type: 'image',
      title: 'Tundra landscape',
      assetId: 'biomes-tundra-alpine',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'tundra-plants-1', text: { en: 'Plants: mosses, grasses, shrubs, dwarf trees', zhHant: '植物：苔蘚、草、灌木、矮樹' } },
      { id: 'tundra-plants-2', text: { en: 'Short summer growing season', zhHant: '短暫的夏季生長季' } },
      { id: 'tundra-plants-3', text: { en: 'Long summer daylight; the sun does not set during mid-summer.', zhHant: '夏季日照很長；仲夏時太陽不會落下。' } },
    ],
    teacherNote: 'Source slide 114. This slide supplies the plant and daylight evidence needed for accurate tundra explanations.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-tundra-animals',
    title: { en: 'Tundra animals', zhHant: '苔原動物' },
    body: {
      en: 'Insects are plentiful in summer. Birds eat the insects, migrate south when winter approaches, and animals grow thick fur coats to stay warm.',
      zhHant: '夏季昆蟲很多。鳥類會吃昆蟲，冬天接近時向南遷徙，而動物長出厚毛皮保暖。',
    },
    visual: 'ecosystem',
    layout: 'image-focus',
    biomeKey: 'tundra',
    emphasis: 'migration + thick fur',
    media: {
      type: 'image',
      title: 'Tundra landscape',
      assetId: 'biomes-tundra-alpine',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'tundra-animals-1', text: { en: 'Summer insects are plentiful.', zhHant: '夏季昆蟲很多。' } },
      { id: 'tundra-animals-2', text: { en: 'Birds eat insects, then migrate south before winter.', zhHant: '鳥類吃昆蟲，冬天前向南遷徙。' } },
      { id: 'tundra-animals-3', text: { en: 'Animals grow thick fur coats to stay warm.', zhHant: '動物長出厚毛皮來保暖。' } },
      { id: 'tundra-animals-4', text: { en: 'Examples: wolves, Arctic hares, caribou', zhHant: '例子：狼、北極兔、馴鹿' } },
    ],
    teacherNote: 'Source slide 115. Keep migration and thick fur as survival evidence, not just animal trivia.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-mountains-ice',
    title: { en: 'Mountains and ice', zhHant: '山地與冰原' },
    body: {
      en: 'Some land areas are not part of any major biome. They include mountain ranges and land covered in thick sheets of ice.',
      zhHant: '有些陸地區域不屬於任何主要生物群系，包括山脈和被厚冰層覆蓋的土地。',
    },
    visual: 'graph',
    layout: 'image-focus',
    biomeKey: 'mountains',
    emphasis: 'not part of any major biome',
    media: {
      type: 'image',
      title: 'Mountain glacier ice',
      assetId: 'biomes-mountains-ice',
    },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'mountains-1', text: { en: 'Mountain ranges are not one major biome.', zhHant: '山脈不是單一主要生物群系。' } },
      { id: 'mountains-2', text: { en: 'Thick sheets of ice are also outside the major biome list.', zhHant: '厚冰層覆蓋的土地也不在主要生物群系列表中。' } },
      { id: 'mountains-3', text: { en: 'As you go up mountains, you experience many different biomes.', zhHant: '沿著山往上走時，會經歷許多不同的生物群系。' } },
    ],
    teacherNote: 'Source slide 116. Treat this as an exception and extension, not a seventh major biome.',
    sourceId: 'src-j1-ch2-4-ppt',
  },
  {
    id: 'j1-ch2-4-rainfall-spectrum',
    title: { en: 'Cumulative rainfall review', zhHant: '降雨量總複習' },
    body: {
      en: 'Use precipitation as evidence: desert, prairie, savanna, deciduous forest, and rain forest show different rainfall conditions.',
      zhHant: '用降水量作為證據：沙漠、大草原、稀樹草原、落葉林和雨林顯示不同的降雨條件。',
    },
    visual: 'graph',
    layout: 'comparison',
    emphasis: 'less rain -> more rain',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'spectrum-1', text: { en: 'Desert: less than 25 cm per year', zhHant: '沙漠：每年少於 25 公分' } },
      { id: 'spectrum-2', text: { en: 'Prairie: 25-75 cm per year', zhHant: '大草原：每年 25-75 公分' } },
      { id: 'spectrum-3', text: { en: 'Savanna: 120 cm per year', zhHant: '稀樹草原：每年 120 公分' } },
      { id: 'spectrum-4', text: { en: 'Rain forest: about 300 cm per year', zhHant: '雨林：每年約 300 公分' } },
    ],
    teacherNote: 'Generated review from source rainfall facts. Use this before assessment review so students answer with evidence.',
    sourceId: 'src-j1-ch2-4-notes',
  },
  {
    id: 'j1-ch2-4-assessment-readiness',
    title: { en: 'Assessment readiness', zhHant: '評量準備' },
    body: {
      en: 'Use source evidence to answer the homework and quiz: definitions, six biomes, climate parts, forest layers, rainfall, animals, deciduous trees, and permafrost.',
      zhHant: '使用原始教材證據回答作業和測驗：定義、六大生物群系、氣候部分、森林層次、降雨、動物、落葉樹和永久凍土。',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'prove it with source evidence',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'assess-1', text: { en: 'Name the six major biomes.', zhHant: '說出六大主要生物群系。' } },
      { id: 'assess-2', text: { en: 'Explain canopy, understory, deciduous, coniferous, and permafrost.', zhHant: '解釋樹冠層、林下層、落葉、針葉和永久凍土。' } },
      { id: 'assess-3', text: { en: 'Match each biome to its evidence.', zhHant: '把每個生物群系配對到它的證據。' } },
      { id: 'assess-4', text: { en: 'Check the homework and quiz resources after teaching.', zhHant: '教學後檢查作業和測驗資源。' } },
    ],
    teacherNote: 'Use this to close the complete unit and align to all 20 assessment questions. Do not rewrite the original homework or quiz here.',
    sourceId: 'src-j1-ch2-4-quiz',
  },
]

export const j1Ch24BiomesLessons: ScienceLesson[] = [
  {
    id: 'j1-ch2-4-biomes-lesson-1',
    unitId: 'j1-ch2-biomes',
    title: 'What Is a Biome? Climate and Major Examples',
    subtitle: 'Chapter 2.4 introduction, climate factors, rain forest, desert, and grassland',
    year: 'J1',
    semester: 'Fall',
    chapter: 'Ch.2.4',
    lessonOrder: 0,
    duration: 50,
    status: 'Published',
    updated: '12 August 2026',
    objectives: [
      'Define biome using similar climates and organisms.',
      'Identify temperature and precipitation as the two climate parts that help determine a biome.',
      'Name the six major biomes from the source curriculum.',
      'Compare rain forest, desert, and grassland using rainfall, layers, vegetation, and animal evidence.',
    ],
    sourceReferences,
    slides: lesson1Slides,
    resources: sharedResources,
  },
  {
    id: 'j1-ch2-4-biomes-lesson-2',
    unitId: 'j1-ch2-biomes',
    title: 'Forests, Tundra, Mountains and Ice',
    subtitle: 'Deciduous forest, boreal forest, tundra, mountains and assessment review',
    year: 'J1',
    semester: 'Fall',
    chapter: 'Ch.2.4',
    lessonOrder: 1,
    duration: 50,
    status: 'Published',
    updated: '12 August 2026',
    objectives: [
      'Explain deciduous forest evidence: leaf shedding, rainfall, growing season, and animals.',
      'Describe boreal forest plants and animals using coniferous trees, cones, needles, herbivores, and carnivores.',
      'Explain tundra climate, permafrost, marsh formation, plants, short summer growth, migration, and thick fur.',
      'Use source evidence to prepare for the original homework and quiz.',
    ],
    sourceReferences,
    slides: lesson2Slides,
    resources: sharedResources,
  },
]
