import type { LessonSlide, ScienceLesson } from '../../types/lesson'

const driveUrl = (id: string) => `https://drive.google.com/file/d/${id}/view`

const sourceReferences = [
  {
    id: 'src-j1-ch1-s1-source-ppt',
    type: 'presentation' as const,
    title: 'Copy of J1 PPT.pptx',
    location: 'Google Drive / J1Science',
    driveFileId: '1STwllX6-z931Hsqst_A1FvN7xwLCVI0g',
    url: 'https://docs.google.com/presentation/d/1STwllX6-z931Hsqst_A1FvN7xwLCVI0g/edit',
    slideRange: 'Source slides 1-15: Chapter 1 Section 1, habitats, abiotic and biotic factors, and levels of organization',
    notes:
      'Authoritative J1 source deck. This lesson preserves the original fifteen-slide teaching sequence instead of compressing it.',
  },
  {
    id: 'src-j1-opening-gold-preview',
    type: 'manual-entry' as const,
    title: 'J1 opening gold-standard web preview',
    location: 'GitHub Pages preview',
    url: '/science-j1-opening-gold.html',
    notes:
      'Interactive source-faithful rebuild: English first, optional Traditional Chinese support, highlight toggle, and click-to-expand teaching areas.',
  },
]

const resources = [
  {
    id: 'j1-opening-source-ppt',
    title: 'Source PPT: Copy of J1 PPT.pptx',
    type: 'Presentation' as const,
    format: 'PPTX' as const,
    detail: 'Authoritative source for Chapter 1 · Section 1, slides 1–15',
    href: 'https://docs.google.com/presentation/d/1STwllX6-z931Hsqst_A1FvN7xwLCVI0g/edit',
    driveFileId: '1STwllX6-z931Hsqst_A1FvN7xwLCVI0g',
    sourceId: 'src-j1-ch1-s1-source-ppt',
    teacherOnly: true,
  },
  {
    id: 'j1-opening-gold-preview',
    title: 'Interactive preview: Chapter 1 · Section 1',
    type: 'Link' as const,
    format: 'Web' as const,
    detail: 'Full source slides 1–15 with classroom controls',
    href: '/science-j1-opening-gold.html',
    sourceId: 'src-j1-opening-gold-preview',
    teacherOnly: false,
  },
  {
    id: 'j1-opening-editable-pptx-old',
    title: 'Previous editable PPT draft: not the teaching standard',
    type: 'Presentation' as const,
    format: 'PPTX' as const,
    detail: 'Earlier compressed draft kept only for audit; this is not the Monday teaching version.',
    href: driveUrl('1Yn9ypEFE2E1TW_3QrZf55iez742CIiwJ'),
    driveFileId: '1Yn9ypEFE2E1TW_3QrZf55iez742CIiwJ',
    teacherOnly: true,
  },
]

const slides: LessonSlide[] = [
  {
    id: 'j1-ch1-1-title',
    title: { en: 'Chapter 1: Section 1', zhHant: '第一章：第一節' },
    body: { en: 'Living Things and the Environment', zhHant: '生物與環境' },
    visual: 'ecosystem',
    layout: 'hero',
    emphasis: 'organisms + environment',
    teacherNote: 'Source slide 1. Open with the big theme before asking the first Question of the Day.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
  {
    id: 'j1-ch1-1-question-needs',
    title: { en: 'Question of the Day', zhHant: '今日問題' },
    body: { en: "What needs are met by an organism's environment?", zhHant: '生物的環境會滿足哪些需求？' },
    visual: 'question',
    layout: 'question',
    teacherNote: 'Source slide 2. Let students predict before vocabulary appears.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
  {
    id: 'j1-ch1-1-habitats',
    title: { en: 'Habitats', zhHant: '棲地' },
    body: { en: 'An organism obtains food, water, shelter, and other things it needs to live, grow, and reproduce from its environment.', zhHant: '生物從環境中獲得生存、生長和繁殖所需的食物、水、庇護所和其他東西。' },
    visual: 'ecosystem',
    layout: 'concept',
    emphasis: 'habitat',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'habitat-definition', text: { en: 'An environment that provides the things the organism needs to live, grow, and reproduce is called its habitat.', zhHant: '能提供生物生存、生長和繁殖所需事物的環境稱為棲地。' } },
    ],
    teacherNote: 'Source slide 3. Keep the original definition, but teach it visually through the four needs.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
  {
    id: 'j1-ch1-1-question-parts',
    title: { en: 'Question of the Day', zhHant: '今日問題' },
    body: { en: "What are the two parts of an organism's habitat with which it interacts?", zhHant: '生物在棲地中會與哪兩個部分互動？' },
    visual: 'question',
    layout: 'question',
    teacherNote: 'Source slide 4. This question sets up abiotic and biotic factors.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
  {
    id: 'j1-ch1-1-abiotic-overview',
    title: { en: 'Abiotic Factors', zhHant: '非生物因子' },
    body: { en: "Abiotic factors are the nonliving parts of an organism's habitat.", zhHant: '非生物因子是生物棲地中沒有生命的部分。' },
    visual: 'ecosystem',
    layout: 'diagram',
    emphasis: 'abiotic factors',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'abiotic-list', text: { en: 'These factors are water, sunlight, oxygen, temperature and soil.', zhHant: '這些因子包括水、陽光、氧氣、溫度和土壤。' } },
    ],
    teacherNote: 'Source slide 5. This needs a large factor diagram, not tiny bullets.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
  {
    id: 'j1-ch1-1-biotic-factors',
    title: { en: 'Biotic Factors', zhHant: '生物因子' },
    body: { en: 'An organism interacts with both the living and nonliving parts of its habitat.', zhHant: '生物會與棲地中有生命和沒有生命的部分互動。' },
    visual: 'ecosystem',
    layout: 'comparison',
    emphasis: 'biotic factors',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'biotic-definition', text: { en: 'The living parts of a habitat are called biotic factors.', zhHant: '棲地中有生命的部分稱為生物因子。' } },
      { id: 'biotic-examples', text: { en: 'Animals and plants in the habitat are biotic factors. Examples include wolves, birds, plants, seeds and fish.', zhHant: '棲地中的動物和植物都是生物因子，例如狼、鳥、植物、種子和魚。' } },
    ],
    teacherNote: 'Source slide 6. Pair this with the abiotic slide so students classify examples.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
  {
    id: 'j1-ch1-1-water',
    title: { en: 'Abiotic Factors: Water', zhHant: '非生物因子：水' },
    body: { en: 'Plants and algae need water, along with sunlight and carbon dioxide, to make their own food in photosynthesis.', zhHant: '植物和藻類需要水、陽光和二氧化碳來進行光合作用製造食物。' },
    visual: 'ecosystem',
    layout: 'image-focus',
    emphasis: 'water',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'water-bodies', text: { en: 'Water makes up a large part of the bodies of most organisms.', zhHant: '水佔大多數生物身體很大的一部分。' } },
      { id: 'water-life', text: { en: 'All things need water to live.', zhHant: '所有生物都需要水才能生存。' } },
    ],
    teacherNote: 'Source slide 7. Teach water as both a body material and a photosynthesis requirement.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
  {
    id: 'j1-ch1-1-sunlight',
    title: { en: 'Abiotic Factors: Sunlight', zhHant: '非生物因子：陽光' },
    body: { en: 'Sunlight is needed for photosynthesis in plants.', zhHant: '植物進行光合作用需要陽光。' },
    visual: 'ecosystem',
    layout: 'image-focus',
    emphasis: 'sunlight',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'no-sunlight', text: { en: "In places that don't get sunlight, plants and algae cannot grow.", zhHant: '在沒有陽光的地方，植物和藻類無法生長。' } },
      { id: 'few-organisms', text: { en: 'Few organisms can live where sunlight cannot reach.', zhHant: '陽光無法到達的地方，只有少數生物能生存。' } },
    ],
    teacherNote: 'Source slide 8. Make the sunlight link to plants explicit.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
  {
    id: 'j1-ch1-1-oxygen',
    title: { en: 'Abiotic Factors: Oxygen', zhHant: '非生物因子：氧氣' },
    body: { en: 'Most living things need oxygen to live.', zhHant: '大多數生物需要氧氣才能生存。' },
    visual: 'ecosystem',
    layout: 'image-focus',
    emphasis: 'oxygen',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'oxygen-land', text: { en: 'Organisms on land get oxygen from the air.', zhHant: '陸地上的生物從空氣中獲得氧氣。' } },
      { id: 'oxygen-water', text: { en: 'Fish and water organisms get oxygen from the water around them.', zhHant: '魚類和水生生物從周圍的水中獲得氧氣。' } },
    ],
    teacherNote: 'Source slide 9. Show air oxygen and dissolved oxygen as two contexts.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
  {
    id: 'j1-ch1-1-temperature',
    title: { en: 'Abiotic Factors: Temperature', zhHant: '非生物因子：溫度' },
    body: { en: 'Temperatures of an area determine the organisms that will live there.', zhHant: '一個地區的溫度會決定哪些生物能在那裡生活。' },
    visual: 'ecosystem',
    layout: 'image-focus',
    emphasis: 'temperature',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'temperature-adapt', text: { en: 'Some animals can change their way of living to adapt to the temperatures of that environment: hot or cold.', zhHant: '有些動物能改變生活方式，以適應該環境的溫度：炎熱或寒冷。' } },
    ],
    teacherNote: 'Source slide 10. This should be a hot/cold contrast, not text alone.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
  {
    id: 'j1-ch1-1-soil',
    title: { en: 'Abiotic Factors: Soil', zhHant: '非生物因子：土壤' },
    body: { en: 'Soil is a mixture of rock pieces, nutrients, air, water, and the decaying remains of living things.', zhHant: '土壤是岩石碎片、養分、空氣、水和生物腐爛遺骸的混合物。' },
    visual: 'ecosystem',
    layout: 'image-focus',
    emphasis: 'soil',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'soil-different', text: { en: 'Soil in different areas contains different amounts of these materials.', zhHant: '不同地區的土壤含有不同數量的這些物質。' } },
      { id: 'soil-organisms', text: { en: 'The type of soil in an area influences the type of organisms living there.', zhHant: '一個地區的土壤類型會影響生活在那裡的生物種類。' } },
    ],
    teacherNote: 'Source slide 11. Use a soil cross-section visual so the mixture is visible.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
  {
    id: 'j1-ch1-1-question-levels',
    title: { en: 'Question of the Day', zhHant: '今日問題' },
    body: { en: 'What are the levels of organization within an ecosystem?', zhHant: '生態系中的組織層次有哪些？' },
    visual: 'question',
    layout: 'question',
    teacherNote: 'Source slide 12. The next three slides build population, community, ecosystem.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
  {
    id: 'j1-ch1-1-populations',
    title: { en: 'Levels of Organization: Populations', zhHant: '組織層次：族群' },
    body: { en: 'A species is a group of organisms that are physically similar and can mate with each other and produce offspring.', zhHant: '物種是一群外形相似，並能彼此交配產生後代的生物。' },
    visual: 'ecosystem',
    layout: 'diagram',
    emphasis: 'population',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'population-definition', text: { en: 'All the members of one species in an area are called the population.', zhHant: '同一地區中同一物種的所有成員稱為族群。' } },
    ],
    teacherNote: 'Source slide 13. Use repeated organisms of one species so population is visually obvious.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
  {
    id: 'j1-ch1-1-communities',
    title: { en: 'Levels of Organization: Communities', zhHant: '組織層次：群落' },
    body: { en: 'A particular area contains more than one species of organisms.', zhHant: '一個特定地區包含不只一種生物。' },
    visual: 'ecosystem',
    layout: 'diagram',
    emphasis: 'community',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'community-definition', text: { en: 'All the different populations that live together in an area make up a community.', zhHant: '生活在同一地區的所有不同族群組成一個群落。' } },
      { id: 'community-interaction', text: { en: 'The different populations must live close together to interact.', zhHant: '不同族群必須生活得夠近，才能互動。' } },
    ],
    teacherNote: 'Source slide 14. Contrast one species population with multi-species community.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
  {
    id: 'j1-ch1-1-ecosystems',
    title: { en: 'Levels of Organization: Ecosystems', zhHant: '組織層次：生態系' },
    body: { en: 'An ecosystem is a community of organisms that live in a particular area, along with their nonliving surroundings.', zhHant: '生態系是生活在特定區域中的生物群落，加上周圍的非生物環境。' },
    visual: 'ecosystem',
    layout: 'diagram',
    emphasis: 'ecosystem',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'ecology-definition', text: { en: 'The study of how living things interact with each other and with their environment is called ecology.', zhHant: '研究生物如何彼此互動以及如何與環境互動的學科稱為生態學。' } },
    ],
    teacherNote: 'Source slide 15. Finish with the hierarchy and connect ecology to interaction.',
    sourceId: 'src-j1-ch1-s1-source-ppt',
  },
]

export const j1OpeningLessons: ScienceLesson[] = [
  {
    id: 'j1-ch1-1-habitats-ecosystems-opening',
    unitId: 'j1-fall-life-ecosystems',
    title: 'Chapter 1 · Section 1 — Living Things and the Environment',
    subtitle: 'Source slides 1–15: Living Things and the Environment, from habitats through levels of organization',
    year: 'J1',
    semester: 'Fall',
    chapter: 'Chapter 1 · Section 1',
    lessonOrder: -10,
    duration: 50,
    status: 'Published',
    updated: '29 August 2026',
    objectives: [
      "Answer: What needs are met by an organism's environment?",
      'Define habitat using food, water, shelter, growth and reproduction.',
      'Classify examples as biotic or abiotic factors.',
      'Explain water, sunlight, oxygen, temperature and soil as abiotic factors.',
      'Explain species, population, community, ecosystem and ecology as levels of organization.',
    ],
    sourceReferences,
    slides,
    resources,
    presentation: { kind: 'courseware', sectionId: 'j1-ch1-s1' },
  },
]
