import type { LessonSlide, ScienceLesson } from '../../types/lesson'
import { formatSourceSectionLabel, sourceSectionMappingByUnitId } from '../curriculumSourceMap'

const reactionsSectionLabel = formatSourceSectionLabel(sourceSectionMappingByUnitId['j1-fall-reactions'])
const solutionsSectionLabel = formatSourceSectionLabel(sourceSectionMappingByUnitId['j1-spring-solutions'])

const j1ReactionSources = [
  {
    id: 'src-j1-ch2-reactions-ppt',
    type: 'presentation' as const,
    title: 'Copy of J1 PPT.pptx',
    location: 'Google Drive / J1Science',
    notes:
      'Recovered J1 source presentation used by the pilot Chemical Reactions lessons. Exact source slide ranges are not yet mapped; this production pass preserves the recovered activation energy, catalyst, and endothermic/exothermic sequence without claiming a verified slide range.',
  },
  {
    id: 'src-j1-ch2-reactions-pilot',
    type: 'manual-entry' as const,
    title: 'Recovered Science Lessons pilot: Chemical Reactions',
    location: 'science-lessons-pilot branch / src/science-lessons/curriculum/j1/pilotLessons.ts',
    notes:
      'Original recovered pilot supplied the unit topics, key vocabulary, objectives, and starter teaching notes for activation energy, catalysts, and energy-change reactions.',
  },
]

const reactionResources = [
  {
    id: 'j1-ch2-reactions-source-ppt',
    title: 'Source PPT: Copy of J1 PPT.pptx',
    type: 'Presentation' as const,
    format: 'PPTX' as const,
    detail: 'Drive source - J1 Chapter 2 reaction sequence; exact slide range pending',
    sourceId: 'src-j1-ch2-reactions-ppt',
    teacherOnly: true,
  },
  {
    id: 'j1-ch2-reactions-board-plan',
    title: 'Teacher board plan: reaction energy diagrams',
    type: 'Classwork' as const,
    format: 'Web' as const,
    detail: 'Use the built-in slide diagrams for board modelling',
    sourceId: 'src-j1-ch2-reactions-pilot',
    teacherOnly: true,
  },
]

const j1SolutionSources = [
  {
    id: 'src-j1-ch3-solutions-ppt',
    type: 'presentation' as const,
    title: 'Copy of J1 PPT.pptx',
    location: 'Google Drive / J1Science',
    notes:
      'Recovered J1 source presentation for Unit 3: Solutions and Solubility. Exact source slide ranges and original solubility-curve data are not yet mapped, so this production pass preserves the recovered concepts without inventing numeric curve values.',
  },
  {
    id: 'src-j1-ch3-solutions-pilot',
    type: 'manual-entry' as const,
    title: 'Recovered Science Lessons pilot: Concentration and Solubility',
    location: 'science-lessons-pilot branch / src/science-lessons/curriculum/j1/pilotLessons.ts',
    notes:
      'Original recovered pilot supplied concentration, saturation, solubility-curve reading steps, starter teaching notes, and the linked solubility practice/review resource titles.',
  },
]

const solutionResources = [
  {
    id: 'j1-ch3-solutions-source-ppt',
    title: 'Source PPT: Copy of J1 PPT.pptx',
    type: 'Presentation' as const,
    format: 'PPTX' as const,
    detail: 'Drive source - J1 Unit 3 solutions sequence; exact slide range pending',
    sourceId: 'src-j1-ch3-solutions-ppt',
    teacherOnly: true,
  },
  {
    id: 'j1-ch3-solubility-curve-practice',
    title: 'Solubility-curve practice',
    type: 'Worksheet' as const,
    format: 'PDF' as const,
    detail: 'Recovered pilot resource - PDF, 3 pages; Drive URL pending',
    sourceId: 'src-j1-ch3-solutions-pilot',
  },
  {
    id: 'j1-ch3-solubility-review-quiz',
    title: 'Solubility review quiz',
    type: 'Quiz' as const,
    format: 'Google Forms' as const,
    detail: 'Recovered pilot resource - editable, 10 questions; Drive URL pending',
    sourceId: 'src-j1-ch3-solutions-pilot',
  },
]

const concentrationSaturationSlides: LessonSlide[] = [
  {
    id: 'j1-ch3-solutions-title',
    title: { en: 'Solutions, solutes and solvents', zhHant: '溶液、溶質與溶劑' },
    body: {
      en: 'A solution forms when a solute dissolves evenly in a solvent. Today we use particle models to compare concentration.',
      zhHant: '當溶質均勻溶解在溶劑中時，就會形成溶液。今天我們用粒子模型比較濃度。',
    },
    visual: 'particles',
    layout: 'hero',
    emphasis: 'solute + solvent -> solution',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'solution-title-1', text: { en: 'Solute: the substance that dissolves.', zhHant: '溶質：被溶解的物質。' } },
      { id: 'solution-title-2', text: { en: 'Solvent: the substance that does the dissolving.', zhHant: '溶劑：使溶質溶解的物質。' } },
      { id: 'solution-title-3', text: { en: 'Solution: solute particles spread through the solvent.', zhHant: '溶液：溶質粒子分散在溶劑中。' } },
    ],
    teacherNote: 'Start with a familiar drink-powder example. Ask students to identify which part dissolves and which part does the dissolving before naming the terms.',
    sourceId: 'src-j1-ch3-solutions-ppt',
  },
  {
    id: 'j1-ch3-solution-equation',
    title: { en: 'The solution model', zhHant: '溶液模型' },
    body: {
      en: 'A solution is not just a mixture with visible pieces. The solute particles are spread through the solvent.',
      zhHant: '溶液不只是看得見碎片的混合物。溶質粒子會分散在溶劑中。',
    },
    visual: 'particles',
    layout: 'concept',
    emphasis: 'solute + solvent -> solution',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'solution-equation-1', text: { en: 'Point to the solute before it dissolves.', zhHant: '先指出尚未溶解的溶質。' } },
      { id: 'solution-equation-2', text: { en: 'Point to the solvent.', zhHant: '指出溶劑。' } },
      { id: 'solution-equation-3', text: { en: 'After dissolving, the solute is spread out.', zhHant: '溶解後，溶質會分散開來。' } },
    ],
    teacherNote: 'Require students to use the words solute, solvent, and solution in one spoken sentence.',
    sourceId: 'src-j1-ch3-solutions-pilot',
  },
  {
    id: 'j1-ch3-concentration-model',
    title: { en: 'What is concentration?', zhHant: '什麼是濃度？' },
    body: {
      en: 'Concentration describes how much solute is dissolved in a particular volume of solution.',
      zhHant: '濃度描述在特定體積的溶液中溶解了多少溶質。',
    },
    visual: 'particles',
    layout: 'comparison',
    emphasis: 'same volume, different solute amount',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'concentration-model-1', text: { en: 'Same-size containers: compare equal volumes.', zhHant: '相同大小的容器：比較相同體積。' } },
      { id: 'concentration-model-2', text: { en: 'More dissolved solute particles means more concentrated.', zhHant: '溶解的溶質粒子越多，濃度越高。' } },
      { id: 'concentration-model-3', text: { en: 'Less dissolved solute means more dilute.', zhHant: '溶解的溶質較少，表示較稀。' } },
    ],
    teacherNote: 'Recovered pilot comparison: two cups with equal volume but different drink-powder amounts. Keep the volume equal so students focus on dissolved solute amount.',
    sourceId: 'src-j1-ch3-solutions-pilot',
  },
  {
    id: 'j1-ch3-dilute-concentrated',
    title: { en: 'Dilute and concentrated', zhHant: '稀溶液與濃溶液' },
    body: {
      en: 'Dilute and concentrated compare relative amounts of dissolved solute. They do not tell us whether the solution has reached its maximum.',
      zhHant: '稀溶液與濃溶液比較已溶解溶質的相對多少。它們不表示溶液是否已達到最大溶解量。',
    },
    visual: 'particles',
    layout: 'comparison',
    emphasis: 'relative amount of solute',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'dilute-concentrated-1', text: { en: 'Dilute: fewer solute particles in the same volume.', zhHant: '稀溶液：相同體積中溶質粒子較少。' } },
      { id: 'dilute-concentrated-2', text: { en: 'Concentrated: more solute particles in the same volume.', zhHant: '濃溶液：相同體積中溶質粒子較多。' } },
      { id: 'dilute-concentrated-3', text: { en: 'This is different from saturated or unsaturated.', zhHant: '這和飽和或未飽和不同。' } },
    ],
    teacherNote: 'Flag the misconception explicitly: concentrated does not automatically mean saturated, and dilute does not automatically mean unsaturated.',
    sourceId: 'src-j1-ch3-solutions-ppt',
  },
  {
    id: 'j1-ch3-concentration-volume',
    title: { en: 'Volume matters when comparing concentration', zhHant: '比較濃度時，體積也很重要' },
    body: {
      en: 'To compare concentration fairly, pay attention to both the amount of solute and the volume of solution.',
      zhHant: '要公平比較濃度，需要同時注意溶質的量和溶液的體積。',
    },
    visual: 'particles',
    layout: 'diagram',
    emphasis: 'solute amount compared with volume',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'concentration-volume-1', text: { en: 'Ask: Are the volumes the same?', zhHant: '先問：體積相同嗎？' } },
      { id: 'concentration-volume-2', text: { en: 'Ask: How much solute is dissolved?', zhHant: '再問：溶解了多少溶質？' } },
      { id: 'concentration-volume-3', text: { en: 'Use both clues before deciding concentrated or dilute.', zhHant: '判斷濃或稀之前，要同時使用兩個線索。' } },
    ],
    teacherNote: 'The recovered unit metadata includes volume, but no calculation equation is present locally. Teach the comparison idea without adding calculation complexity.',
    sourceId: 'src-j1-ch3-solutions-ppt',
  },
  {
    id: 'j1-ch3-saturation-sequence',
    title: { en: 'When no more solute dissolves', zhHant: '當無法再溶解更多溶質時' },
    body: {
      en: 'A saturated solution contains the maximum amount of dissolved solute at that temperature.',
      zhHant: '飽和溶液在該溫度下含有最大量的已溶解溶質。',
    },
    visual: 'experiment',
    layout: 'diagram',
    emphasis: 'maximum dissolved solute',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'saturation-sequence-1', text: { en: 'Add a small amount of solute: it dissolves.', zhHant: '加入少量溶質：它會溶解。' } },
      { id: 'saturation-sequence-2', text: { en: 'Add more solute: it still dissolves.', zhHant: '再加入更多溶質：仍然會溶解。' } },
      { id: 'saturation-sequence-3', text: { en: 'Add too much: some solid remains undissolved.', zhHant: '加入過多時：有些固體會留在底部，無法溶解。' } },
      { id: 'saturation-sequence-4', text: { en: 'Evidence for saturation: no more dissolves at this temperature.', zhHant: '飽和的證據：在此溫度下無法再溶解更多。' } },
    ],
    teacherNote: 'Ask what evidence would show that no more solute can dissolve. Expected response: undissolved solid remains even after stirring.',
    sourceId: 'src-j1-ch3-solutions-pilot',
  },
  {
    id: 'j1-ch3-unsaturated-saturated',
    title: { en: 'Unsaturated or saturated?', zhHant: '未飽和還是飽和？' },
    body: {
      en: 'An unsaturated solution can still dissolve more solute. A saturated solution cannot dissolve more solute at that temperature.',
      zhHant: '未飽和溶液仍可以溶解更多溶質。飽和溶液在該溫度下無法再溶解更多溶質。',
    },
    visual: 'experiment',
    layout: 'comparison',
    emphasis: 'can dissolve more?',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'unsaturated-saturated-1', text: { en: 'Unsaturated: more solute can still dissolve.', zhHant: '未飽和：仍可溶解更多溶質。' } },
      { id: 'unsaturated-saturated-2', text: { en: 'Saturated: maximum dissolved amount has been reached.', zhHant: '飽和：已達最大可溶解量。' } },
      { id: 'unsaturated-saturated-3', text: { en: 'Do not use colour strength alone as evidence.', zhHant: '不要只用顏色深淺作為證據。' } },
    ],
    teacherNote: 'Separate the two comparisons: dilute/concentrated is about relative solute amount; saturated/unsaturated is about whether more can dissolve.',
    sourceId: 'src-j1-ch3-solutions-ppt',
  },
  {
    id: 'j1-ch3-concentration-exit',
    title: { en: 'Exit check: explain the evidence', zhHant: '課堂檢核：解釋證據' },
    body: {
      en: 'Two same-size cups contain different amounts of dissolved drink powder. Which is more concentrated, and how do you know?',
      zhHant: '兩個相同大小的杯子含有不同量的已溶解飲料粉。哪一杯濃度較高？你怎麼知道？',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'use solute and volume',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'concentration-exit-1', text: { en: 'Compare equal volumes first.', zhHant: '先確認比較的是相同體積。' } },
      { id: 'concentration-exit-2', text: { en: 'More dissolved solute means higher concentration.', zhHant: '已溶解溶質較多，表示濃度較高。' } },
      { id: 'concentration-exit-3', text: { en: 'Saturation needs separate evidence: can more dissolve?', zhHant: '飽和需要另一個證據：還能再溶解嗎？' } },
    ],
    teacherNote: 'Collect one sentence using concentration, solute, solution, and volume. Bonus: ask why this does not prove saturation.',
    sourceId: 'src-j1-ch3-solutions-pilot',
  },
]

const solubilityCurveSlides: LessonSlide[] = [
  {
    id: 'j1-ch3-solubility-title',
    title: { en: 'Solubility and temperature', zhHant: '溶解度與溫度' },
    body: {
      en: 'Solubility tells us the maximum amount of solute that can dissolve at a particular temperature.',
      zhHant: '溶解度告訴我們在特定溫度下最多可以溶解多少溶質。',
    },
    visual: 'graph',
    layout: 'hero',
    emphasis: 'maximum dissolved at a temperature',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'solubility-title-1', text: { en: 'Solubility is about the maximum amount.', zhHant: '溶解度關於最大可溶解量。' } },
      { id: 'solubility-title-2', text: { en: 'The temperature must be stated.', zhHant: '必須說明溫度。' } },
      { id: 'solubility-title-3', text: { en: 'Use the source curve for exact values.', zhHant: '精確數值要使用來源曲線。' } },
    ],
    teacherNote: 'Define solubility using the recovered pilot wording: maximum mass of solute that dissolves at each temperature.',
    sourceId: 'src-j1-ch3-solutions-pilot',
  },
  {
    id: 'j1-ch3-solubility-definition',
    title: { en: 'Solubility is a maximum', zhHant: '溶解度是一個最大值' },
    body: {
      en: 'At the same temperature, a solution can be below the maximum, exactly at the maximum, or past the maximum with undissolved solid present.',
      zhHant: '在相同溫度下，溶液可能低於最大值、剛好達到最大值，或超過最大值而有未溶解固體存在。',
    },
    visual: 'experiment',
    layout: 'diagram',
    emphasis: 'maximum dissolved solute',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'solubility-definition-1', text: { en: 'Below maximum: more can dissolve.', zhHant: '低於最大值：還能再溶解。' } },
      { id: 'solubility-definition-2', text: { en: 'At maximum: saturated.', zhHant: '達到最大值：飽和。' } },
      { id: 'solubility-definition-3', text: { en: 'Past maximum: extra solid remains undissolved.', zhHant: '超過最大值：多餘固體不會溶解。' } },
    ],
    teacherNote: 'Connect back to Lesson 1. Saturation is judged by whether the maximum dissolved amount has been reached at that temperature.',
    sourceId: 'src-j1-ch3-solutions-ppt',
  },
  {
    id: 'j1-ch3-temperature-solubility',
    title: { en: 'Temperature changes the reading', zhHant: '溫度會改變讀取值' },
    body: {
      en: 'A solubility curve lets us check the maximum dissolved amount at different temperatures for the substance shown.',
      zhHant: '溶解度曲線讓我們查出圖中物質在不同溫度下的最大可溶解量。',
    },
    visual: 'graph',
    layout: 'concept',
    emphasis: 'temperature + solubility',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'temperature-solubility-1', text: { en: 'Do not assume every substance has the same pattern.', zhHant: '不要假設每種物質都有相同趨勢。' } },
      { id: 'temperature-solubility-2', text: { en: 'Read the curve for the substance in the question.', zhHant: '閱讀題目指定物質的曲線。' } },
      { id: 'temperature-solubility-3', text: { en: 'Then match temperature to solubility.', zhHant: '再把溫度對應到溶解度。' } },
    ],
    teacherNote: 'The local recovered source confirms temperature-based curve reading but not a universal trend. Avoid saying all solutes increase with temperature.',
    sourceId: 'src-j1-ch3-solutions-ppt',
  },
  {
    id: 'j1-ch3-solubility-curve-axes',
    title: { en: 'Read the axes first', zhHant: '先閱讀座標軸' },
    body: {
      en: 'The x-axis shows temperature. The y-axis shows the maximum mass of solute that dissolves.',
      zhHant: 'x 軸顯示溫度。y 軸顯示可溶解的最大溶質質量。',
    },
    visual: 'graph',
    layout: 'comparison',
    emphasis: 'x-axis temperature, y-axis mass',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'curve-axes-1', text: { en: 'Find the substance or curve named in the question.', zhHant: '找出題目指定的物質或曲線。' } },
      { id: 'curve-axes-2', text: { en: 'Check the x-axis: temperature.', zhHant: '檢查 x 軸：溫度。' } },
      { id: 'curve-axes-3', text: { en: 'Check the y-axis: maximum mass of solute.', zhHant: '檢查 y 軸：最大溶質質量。' } },
    ],
    teacherNote: 'Make students point to both axes before asking for any value. This prevents reading the graph backwards.',
    sourceId: 'src-j1-ch3-solutions-pilot',
  },
  {
    id: 'j1-ch3-graph-reading-crosshair',
    title: { en: 'Use a graph-reading crosshair', zhHant: '使用圖表讀取輔助線' },
    body: {
      en: 'Choose the temperature, move up to the curve, then move across to read the solubility value.',
      zhHant: '選擇溫度，向上移動到曲線，再水平移動讀取溶解度數值。',
    },
    visual: 'graph',
    layout: 'comparison',
    emphasis: 'temperature -> curve -> solubility',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'graph-reading-1', text: { en: 'Choose the temperature on the x-axis.', zhHant: '在 x 軸選擇溫度。' } },
      { id: 'graph-reading-2', text: { en: 'Move up to the curve.', zhHant: '向上移動到曲線。' } },
      { id: 'graph-reading-3', text: { en: 'Move across to the y-axis.', zhHant: '水平移動到 y 軸。' } },
      { id: 'graph-reading-4', text: { en: 'Read the mass on the y-axis.', zhHant: '在 y 軸讀取質量。' } },
    ],
    teacherNote: 'Recovered pilot sequence preserved. The built-in curve is a teaching schematic because exact source data is not locally recovered; use the source worksheet/PPT for assessed numeric answers.',
    sourceId: 'src-j1-ch3-solutions-pilot',
  },
  {
    id: 'j1-ch3-compare-curves',
    title: { en: 'Compare curves at one temperature', zhHant: '在同一溫度比較曲線' },
    body: {
      en: 'If a source graph has several substances, compare them at the same temperature before deciding which has the greater solubility.',
      zhHant: '如果來源圖表有多種物質，要在相同溫度下比較，再判斷哪一種溶解度較高。',
    },
    visual: 'graph',
    layout: 'comparison',
    emphasis: 'same temperature, different curves',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'compare-curves-1', text: { en: 'Use one temperature line for every curve.', zhHant: '每條曲線都使用同一條溫度線。' } },
      { id: 'compare-curves-2', text: { en: 'The higher curve at that temperature has greater solubility.', zhHant: '在該溫度下，位置較高的曲線代表溶解度較高。' } },
      { id: 'compare-curves-3', text: { en: 'Do not compare two curves at different temperatures.', zhHant: '不要在不同溫度下比較兩條曲線。' } },
    ],
    teacherNote: 'No specific multi-curve data is recovered locally. Use this as a method slide before students work from the actual source graph.',
    sourceId: 'src-j1-ch3-solutions-ppt',
  },
  {
    id: 'j1-ch3-on-below-above-curve',
    title: { en: 'Below, on, or above the curve', zhHant: '曲線下、曲線上或曲線上方' },
    body: {
      en: 'A point on the curve represents the maximum dissolved amount. Points below the curve can still dissolve more; points above the curve leave extra solid undissolved.',
      zhHant: '曲線上的點代表最大可溶解量。曲線下方仍可再溶解；曲線上方會有多餘固體無法溶解。',
    },
    visual: 'graph',
    layout: 'comparison',
    emphasis: 'below, on, above',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'below-on-above-1', text: { en: 'Below curve: unsaturated.', zhHant: '曲線下方：未飽和。' } },
      { id: 'below-on-above-2', text: { en: 'On curve: saturated.', zhHant: '曲線上：飽和。' } },
      { id: 'below-on-above-3', text: { en: 'Above curve: extra solid remains.', zhHant: '曲線上方：多餘固體會留下。' } },
    ],
    teacherNote: 'This follows directly from the recovered definition of saturation and the recovered curve-as-maximum wording. If the source worksheet omits above/below questions, use as enrichment only.',
    sourceId: 'src-j1-ch3-solutions-pilot',
  },
  {
    id: 'j1-ch3-solubility-exit',
    title: { en: 'Exit check: read then explain', zhHant: '課堂檢核：讀取並解釋' },
    body: {
      en: 'Use the source solubility curve to answer: What temperature did you choose, what curve did you use, and what y-axis value did you read?',
      zhHant: '使用來源溶解度曲線回答：你選了哪個溫度、使用哪條曲線、讀到哪個 y 軸數值？',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'axis, curve, value, interpretation',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'solubility-exit-1', text: { en: 'Name the curve or substance.', zhHant: '說出曲線或物質名稱。' } },
      { id: 'solubility-exit-2', text: { en: 'Name the x-axis temperature.', zhHant: '說出 x 軸溫度。' } },
      { id: 'solubility-exit-3', text: { en: 'Read the y-axis mass and explain what it means.', zhHant: '讀取 y 軸質量，並解釋它的意思。' } },
    ],
    teacherNote: 'Do not give a memorised number. Students should show the path on the graph and state that the value means the maximum mass of solute that dissolves at that temperature.',
    sourceId: 'src-j1-ch3-solutions-pilot',
  },
]

const activationEnergySlides: LessonSlide[] = [
  {
    id: 'j1-ch2-reactions-title',
    title: { en: 'Activation energy and catalysts', zhHant: '活化能與催化劑' },
    body: {
      en: 'Today we explain why particles sometimes need a starting push before a chemical reaction can happen.',
      zhHant: '今天我們要解釋為什麼粒子有時需要一個「開始的推力」，化學反應才會發生。',
    },
    visual: 'particles',
    layout: 'hero',
    emphasis: 'reaction starting push',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'reaction-title-1', text: { en: 'Reactants do not change just because they are near each other.', zhHant: '反應物不會只因為彼此靠近就發生變化。' } },
      { id: 'reaction-title-2', text: { en: 'A successful collision needs enough energy.', zhHant: '成功碰撞需要足夠的能量。' } },
    ],
    teacherNote: 'Open with a low-stakes prediction: why does paper not instantly burn at room temperature? Keep the answer for the activation-energy slide.',
    sourceId: 'src-j1-ch2-reactions-ppt',
  },
  {
    id: 'j1-ch2-reactions-collision-question',
    title: { en: 'What makes a collision successful?', zhHant: '什麼讓碰撞成功？' },
    body: {
      en: 'Particles must collide with enough energy and in the correct orientation before bonds can break and new bonds can form.',
      zhHant: '粒子必須以足夠的能量和正確的方向碰撞，舊鍵才可能斷裂，新鍵才可能形成。',
    },
    visual: 'particles',
    layout: 'question',
    emphasis: 'energy + orientation',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'collision-1', text: { en: 'First condition: particles collide.', zhHant: '第一個條件：粒子互相碰撞。' } },
      { id: 'collision-2', text: { en: 'Second condition: the collision has enough energy.', zhHant: '第二個條件：碰撞具有足夠能量。' } },
      { id: 'collision-3', text: { en: 'Third condition: the orientation is useful for bond changes.', zhHant: '第三個條件：碰撞方向有助於化學鍵改變。' } },
    ],
    teacherNote: 'Ask students to mime a weak bump and a useful bump with hands. Watch for the misconception that every collision causes a reaction.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-reactions-activation-definition',
    title: { en: 'Activation energy', zhHant: '活化能' },
    body: {
      en: 'Activation energy is the minimum energy needed for reacting particles to form products.',
      zhHant: '活化能是反應粒子形成生成物所需要的最低能量。',
    },
    visual: 'graph',
    layout: 'concept',
    emphasis: 'minimum energy for products',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'activation-definition-1', text: { en: 'Reactants begin with stored chemical energy.', zhHant: '反應物一開始具有儲存的化學能。' } },
      { id: 'activation-definition-2', text: { en: 'They must reach the energy barrier.', zhHant: '它們必須達到能量障礙。' } },
      { id: 'activation-definition-3', text: { en: 'After the barrier, products can form.', zhHant: '越過障礙後，生成物才可以形成。' } },
    ],
    teacherNote: 'Define activation energy only after students have named the need for enough energy. Point to "minimum" and ask what happens below that level.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-reactions-energy-profile',
    title: { en: 'Reading the reaction profile', zhHant: '讀懂反應能量圖' },
    body: {
      en: 'A reaction profile shows reactants, the activation-energy barrier, and products.',
      zhHant: '反應能量圖顯示反應物、活化能障礙和生成物。',
    },
    visual: 'graph',
    layout: 'diagram',
    emphasis: 'reactants -> barrier -> products',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'profile-1', text: { en: 'Start: reactants', zhHant: '起點：反應物' } },
      { id: 'profile-2', text: { en: 'Peak: activation-energy barrier', zhHant: '最高點：活化能障礙' } },
      { id: 'profile-3', text: { en: 'End: products', zhHant: '終點：生成物' } },
      { id: 'profile-4', text: { en: 'The higher the barrier, the harder the reaction is to start.', zhHant: '障礙越高，反應越難開始。' } },
    ],
    teacherNote: 'Trace the curve slowly from left to right. Students should say reactants, barrier, products before writing.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-reactions-catalyst-pathway',
    title: { en: 'What does a catalyst change?', zhHant: '催化劑改變了什麼？' },
    body: {
      en: 'A catalyst provides a different reaction pathway with lower activation energy.',
      zhHant: '催化劑提供一條具有較低活化能的不同反應途徑。',
    },
    visual: 'experiment',
    layout: 'comparison',
    emphasis: 'lower activation energy',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'catalyst-pathway-1', text: { en: 'Without catalyst: higher energy barrier', zhHant: '沒有催化劑：能量障礙較高' } },
      { id: 'catalyst-pathway-2', text: { en: 'With catalyst: lower energy barrier', zhHant: '有催化劑：能量障礙較低' } },
      { id: 'catalyst-pathway-3', text: { en: 'More particles can react successfully each second.', zhHant: '每秒有更多粒子能成功反應。' } },
      { id: 'catalyst-pathway-4', text: { en: 'The products are still the same chemical target.', zhHant: '生成物仍然是相同的化學目標。' } },
    ],
    teacherNote: 'Emphasise pathway, not magic. A catalyst does not give unlimited energy; it lowers the barrier for a different route.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-reactions-catalyst-not-used',
    title: { en: 'A catalyst is not used up', zhHant: '催化劑不會被消耗' },
    body: {
      en: 'A catalyst helps the reaction happen faster, but it is not consumed by the overall reaction.',
      zhHant: '催化劑幫助反應更快發生，但在整個反應中不會被消耗。',
    },
    visual: 'experiment',
    layout: 'diagram',
    emphasis: 'helps, then remains',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'catalyst-cycle-1', text: { en: 'Reactants attach or interact.', zhHant: '反應物附著或互相作用。' } },
      { id: 'catalyst-cycle-2', text: { en: 'Products form more easily.', zhHant: '生成物較容易形成。' } },
      { id: 'catalyst-cycle-3', text: { en: 'The catalyst is available again.', zhHant: '催化劑又可以再次使用。' } },
    ],
    teacherNote: 'Ask: if the catalyst is still available, why can a small amount help many particles? Expected idea: it can be reused.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-reactions-rate-check',
    title: { en: 'Explain the rate change', zhHant: '解釋反應速率改變' },
    body: {
      en: 'If activation energy becomes lower, more particle collisions have enough energy to react successfully.',
      zhHant: '如果活化能降低，就會有更多粒子碰撞具有足夠能量並成功反應。',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'more successful collisions',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'rate-check-1', text: { en: 'Prediction: Will the reaction rate increase or decrease?', zhHant: '預測：反應速率會增加還是降低？' } },
      { id: 'rate-check-2', text: { en: 'Answer: increase.', zhHant: '答案：增加。' } },
      { id: 'rate-check-3', text: { en: 'Reason: more collisions reach the lower energy barrier.', zhHant: '原因：更多碰撞能達到較低的能量障礙。' } },
    ],
    teacherNote: 'Give 30 seconds of quiet writing before revealing the answer. Require the words activation energy and successful collision.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-reactions-exit',
    title: { en: 'Exit check: one complete explanation', zhHant: '課堂檢核：完整解釋一句話' },
    body: {
      en: 'Use activation energy, catalyst, and successful collision in one scientific explanation.',
      zhHant: '使用「活化能」、「催化劑」和「成功碰撞」寫出一句科學解釋。',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'use all three terms',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'activation-exit-1', text: { en: 'A catalyst lowers activation energy.', zhHant: '催化劑降低活化能。' } },
      { id: 'activation-exit-2', text: { en: 'More collisions become successful.', zhHant: '更多碰撞會變成成功碰撞。' } },
      { id: 'activation-exit-3', text: { en: 'Therefore the reaction rate increases.', zhHant: '因此反應速率增加。' } },
    ],
    teacherNote: 'Use this as the written exit ticket. Students can combine the three reveal points into one sentence.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
]

const endoExothermicSlides: LessonSlide[] = [
  {
    id: 'j1-ch2-energy-change-title',
    title: { en: 'Endothermic and exothermic reactions', zhHant: '吸熱反應與放熱反應' },
    body: {
      en: 'Chemical reactions can transfer energy into or out of the reaction system.',
      zhHant: '化學反應可以讓能量進入或離開反應系統。',
    },
    visual: 'experiment',
    layout: 'hero',
    emphasis: 'energy moves',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'energy-title-1', text: { en: 'Hand warmer: energy leaves the reaction system.', zhHant: '暖暖包：能量離開反應系統。' } },
      { id: 'energy-title-2', text: { en: 'Cold pack: energy enters the reaction system.', zhHant: '冰敷包：能量進入反應系統。' } },
    ],
    teacherNote: 'Use familiar examples first. Do not define endothermic/exothermic until students have noticed energy direction.',
    sourceId: 'src-j1-ch2-reactions-ppt',
  },
  {
    id: 'j1-ch2-energy-system-surroundings',
    title: { en: 'System and surroundings', zhHant: '系統與周圍環境' },
    body: {
      en: 'The system is the chemicals reacting. The surroundings are everything around the reaction, including the container, air, and your hand.',
      zhHant: '系統是正在反應的化學物質。周圍環境是反應周圍的一切，包括容器、空氣和你的手。',
    },
    visual: 'particles',
    layout: 'concept',
    emphasis: 'track energy direction',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'system-1', text: { en: 'System: reacting chemicals', zhHant: '系統：正在反應的化學物質' } },
      { id: 'system-2', text: { en: 'Surroundings: container, air, hand, thermometer', zhHant: '周圍環境：容器、空氣、手、溫度計' } },
      { id: 'system-3', text: { en: 'Question: Which way does energy move?', zhHant: '問題：能量往哪個方向移動？' } },
    ],
    teacherNote: 'Draw a box for the system. Arrows should cross the box boundary; this prevents students from saying simply "it gets hot" without naming energy direction.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-exothermic',
    title: { en: 'Exothermic reactions release energy', zhHant: '放熱反應釋放能量' },
    body: {
      en: 'In an exothermic reaction, energy is transferred from the system to the surroundings. The surroundings often become warmer.',
      zhHant: '在放熱反應中，能量從系統傳到周圍環境。周圍環境通常會變暖。',
    },
    visual: 'graph',
    layout: 'diagram',
    emphasis: 'energy leaves the system',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'exo-1', text: { en: 'Energy arrow: system -> surroundings', zhHant: '能量箭頭：系統 → 周圍環境' } },
      { id: 'exo-2', text: { en: 'Temperature around the reaction may rise.', zhHant: '反應周圍的溫度可能上升。' } },
      { id: 'exo-3', text: { en: 'Products have less stored energy than reactants.', zhHant: '生成物儲存的能量比反應物少。' } },
    ],
    teacherNote: 'Students often say "the reaction is hot." Reframe it: energy leaves the reacting chemicals and warms the surroundings.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-endothermic',
    title: { en: 'Endothermic reactions absorb energy', zhHant: '吸熱反應吸收能量' },
    body: {
      en: 'In an endothermic reaction, energy is transferred from the surroundings into the system. The surroundings often become cooler.',
      zhHant: '在吸熱反應中，能量從周圍環境傳入系統。周圍環境通常會變冷。',
    },
    visual: 'graph',
    layout: 'diagram',
    emphasis: 'energy enters the system',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'endo-1', text: { en: 'Energy arrow: surroundings -> system', zhHant: '能量箭頭：周圍環境 → 系統' } },
      { id: 'endo-2', text: { en: 'Temperature around the reaction may fall.', zhHant: '反應周圍的溫度可能下降。' } },
      { id: 'endo-3', text: { en: 'Products have more stored energy than reactants.', zhHant: '生成物儲存的能量比反應物多。' } },
    ],
    teacherNote: 'Connect to a cold pack. The pack feels cold because energy is taken from the surroundings into the reaction system.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-energy-profile-compare',
    title: { en: 'Compare energy profiles', zhHant: '比較能量圖' },
    body: {
      en: 'Use the height of products compared with reactants to decide whether the reaction is exothermic or endothermic.',
      zhHant: '比較生成物與反應物的高度，判斷反應是放熱還是吸熱。',
    },
    visual: 'graph',
    layout: 'comparison',
    emphasis: 'products lower or higher?',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'profiles-1', text: { en: 'Products lower than reactants: exothermic', zhHant: '生成物比反應物低：放熱反應' } },
      { id: 'profiles-2', text: { en: 'Products higher than reactants: endothermic', zhHant: '生成物比反應物高：吸熱反應' } },
      { id: 'profiles-3', text: { en: 'Both still need activation energy to start.', zhHant: '兩者仍然都需要活化能才會開始。' } },
    ],
    teacherNote: 'Bring back Lesson 1: both profiles still have an activation-energy barrier. The end height tells the energy-change type.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-classify-examples',
    title: { en: 'Classify the examples', zhHant: '分類例子' },
    body: {
      en: 'Decide whether each example shows energy leaving the system or entering the system.',
      zhHant: '判斷每個例子顯示能量離開系統，還是進入系統。',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'use energy direction',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'classify-1', text: { en: 'Hand warmer: exothermic - energy leaves the system.', zhHant: '暖暖包：放熱反應 — 能量離開系統。' } },
      { id: 'classify-2', text: { en: 'Instant cold pack: endothermic - energy enters the system.', zhHant: '即用冰敷包：吸熱反應 — 能量進入系統。' } },
      { id: 'classify-3', text: { en: 'If the surroundings warm up, the reaction is usually exothermic.', zhHant: '如果周圍環境變暖，反應通常是放熱反應。' } },
      { id: 'classify-4', text: { en: 'If the surroundings cool down, the reaction is usually endothermic.', zhHant: '如果周圍環境變冷，反應通常是吸熱反應。' } },
    ],
    teacherNote: 'Ask students to justify with arrows, not just labels. Expected language: energy moves from/to the system.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-energy-graph-question',
    title: { en: 'Graph check', zhHant: '圖表檢核' },
    body: {
      en: 'A graph ends with products lower than reactants. What type of reaction is it, and how do you know?',
      zhHant: '一張圖中，生成物的位置比反應物低。這是哪一種反應？你怎麼知道？',
    },
    visual: 'graph',
    layout: 'question',
    emphasis: 'products lower than reactants',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'graph-check-1', text: { en: 'Type: exothermic reaction.', zhHant: '種類：放熱反應。' } },
      { id: 'graph-check-2', text: { en: 'Evidence: products have less stored energy.', zhHant: '證據：生成物儲存的能量較少。' } },
      { id: 'graph-check-3', text: { en: 'Energy has been transferred to the surroundings.', zhHant: '能量已經傳到周圍環境。' } },
    ],
    teacherNote: 'This is the representative reveal check. Let students answer before showing the type, then require evidence from the graph.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-energy-exit',
    title: { en: 'Exit check: choose the evidence', zhHant: '課堂檢核：選擇證據' },
    body: {
      en: 'Explain the difference between exothermic and endothermic reactions using system, surroundings, and energy transfer.',
      zhHant: '使用「系統」、「周圍環境」和「能量轉移」解釋放熱反應與吸熱反應的差異。',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'system + surroundings + energy',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'energy-exit-1', text: { en: 'Exothermic: energy leaves the system.', zhHant: '放熱：能量離開系統。' } },
      { id: 'energy-exit-2', text: { en: 'Endothermic: energy enters the system.', zhHant: '吸熱：能量進入系統。' } },
      { id: 'energy-exit-3', text: { en: 'Use temperature change as evidence from the surroundings.', zhHant: '使用周圍環境的溫度變化作為證據。' } },
    ],
    teacherNote: 'Collect a two-column comparison. Strong responses name the direction of energy transfer and one observable temperature clue.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
]

export const j1PilotLessons: ScienceLesson[] = [
  {
    id: 'activation-energy-catalysts',
    unitId: 'j1-fall-reactions',
    title: 'Activation Energy and Catalysts',
    subtitle: 'Why reactions need a starting push and how catalysts lower the energy barrier',
    year: 'J1',
    semester: 'Fall',
    chapter: reactionsSectionLabel,
    lessonOrder: 10,
    duration: 50,
    status: 'Published',
    updated: '13 August 2026',
    objectives: [
      'Describe the energy and orientation conditions needed for a successful particle collision.',
      'Define activation energy as the minimum energy needed for reactants to form products.',
      'Read a simple reaction-profile graph by identifying reactants, activation-energy barrier, and products.',
      'Explain how a catalyst lowers activation energy and increases reaction rate without being used up.',
    ],
    sourceReferences: j1ReactionSources,
    slides: activationEnergySlides,
    resources: reactionResources,
  },
  {
    id: 'endo-exothermic',
    unitId: 'j1-fall-reactions',
    title: 'Endothermic and Exothermic Reactions',
    subtitle: 'Using energy-transfer direction and reaction profiles to classify reactions',
    year: 'J1',
    semester: 'Fall',
    chapter: reactionsSectionLabel,
    lessonOrder: 11,
    duration: 50,
    status: 'Published',
    updated: '13 August 2026',
    objectives: [
      'Identify the reaction system and its surroundings.',
      'Describe exothermic reactions as energy transfer from the system to the surroundings.',
      'Describe endothermic reactions as energy transfer from the surroundings into the system.',
      'Use product and reactant energy levels on a reaction profile to classify energy-change reactions.',
    ],
    sourceReferences: j1ReactionSources,
    slides: endoExothermicSlides,
    resources: reactionResources,
  },
  {
    id: 'j1-concentration-saturation',
    unitId: 'j1-spring-solutions',
    title: 'Concentration, Solutes and Saturation',
    subtitle: 'Using particle models to compare dissolved solute, volume and saturation evidence',
    year: 'J1',
    semester: 'Spring / Summer',
    chapter: solutionsSectionLabel,
    lessonOrder: 1,
    duration: 50,
    status: 'Published',
    updated: '13 August 2026',
    objectives: [
      'Identify solute, solvent and solution in a dissolving model.',
      'Describe concentration as dissolved solute amount compared with solution volume.',
      'Compare dilute and concentrated solutions using particle evidence.',
      'Distinguish dilute/concentrated from unsaturated/saturated using whether more solute can dissolve.',
    ],
    sourceReferences: j1SolutionSources,
    slides: concentrationSaturationSlides,
    resources: solutionResources,
  },
  {
    id: 'j1-solubility-curves',
    unitId: 'j1-spring-solutions',
    title: 'Solubility and Solubility Curves',
    subtitle: 'Reading axes, temperature, maximum dissolved mass and curve evidence',
    year: 'J1',
    semester: 'Spring / Summer',
    chapter: solutionsSectionLabel,
    lessonOrder: 2,
    duration: 50,
    status: 'Published',
    updated: '13 August 2026',
    objectives: [
      'Define solubility as the maximum amount of solute that dissolves at a particular temperature.',
      'Identify temperature on the x-axis and maximum dissolved solute mass on the y-axis.',
      'Use a staged crosshair method to read a solubility curve.',
      'Interpret below/on/above-curve evidence where the source graph asks for it.',
    ],
    sourceReferences: j1SolutionSources,
    slides: solubilityCurveSlides,
    resources: solutionResources,
  },
]
