import type { LessonSlide, ScienceLesson } from '../../types/lesson'

const j1ReactionSources = [
  {
    id: 'src-j1-ch2-reactions-ppt',
    type: 'presentation' as const,
    title: 'Copy of J1 PPT.pptx',
    location: 'Google Drive / J1Science',
    notes:
      'Recovered J1 source presentation used by the pilot Chemical Reactions lessons. Exact source slide ranges are not yet mapped; this production pass preserves the recovered activation energy, catalyst, and endothermic/exothermic sequence without claiming a verified slide range.',
  },
  {
    id: 'src-j1-ch2-reactions-pilot',
    type: 'manual-entry' as const,
    title: 'Recovered Science Lessons pilot: Chemical Reactions',
    location: 'science-lessons-pilot branch / src/science-lessons/curriculum/j1/pilotLessons.ts',
    notes:
      'Original recovered pilot supplied the unit topics, key vocabulary, objectives, and starter teaching notes for activation energy, catalysts, and energy-change reactions.',
  },
]

const reactionResources = [
  {
    id: 'j1-ch2-reactions-source-ppt',
    title: 'Source PPT: Copy of J1 PPT.pptx',
    type: 'Presentation' as const,
    format: 'PPTX' as const,
    detail: 'Drive source - J1 Chapter 2 reaction sequence; exact slide range pending',
    sourceId: 'src-j1-ch2-reactions-ppt',
    teacherOnly: true,
  },
  {
    id: 'j1-ch2-reactions-board-plan',
    title: 'Teacher board plan: reaction energy diagrams',
    type: 'Classwork' as const,
    format: 'Web' as const,
    detail: 'Use the built-in slide diagrams for board modelling',
    sourceId: 'src-j1-ch2-reactions-pilot',
    teacherOnly: true,
  },
]

const activationEnergySlides: LessonSlide[] = [
  {
    id: 'j1-ch2-reactions-title',
    title: { en: 'Activation energy and catalysts', zhHant: '活化能與催化劑' },
    body: {
      en: 'Today we explain why particles sometimes need a starting push before a chemical reaction can happen.',
      zhHant: '今天我們要解釋為什麼粒子有時需要一個「開始的推力」，化學反應才會發生。',
    },
    visual: 'particles',
    layout: 'hero',
    emphasis: 'reaction starting push',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'reaction-title-1', text: { en: 'Reactants do not change just because they are near each other.', zhHant: '反應物不會只因為彼此靠近就發生變化。' } },
      { id: 'reaction-title-2', text: { en: 'A successful collision needs enough energy.', zhHant: '成功碰撞需要足夠的能量。' } },
    ],
    teacherNote: 'Open with a low-stakes prediction: why does paper not instantly burn at room temperature? Keep the answer for the activation-energy slide.',
    sourceId: 'src-j1-ch2-reactions-ppt',
  },
  {
    id: 'j1-ch2-reactions-collision-question',
    title: { en: 'What makes a collision successful?', zhHant: '什麼讓碰撞成功？' },
    body: {
      en: 'Particles must collide with enough energy and in the correct orientation before bonds can break and new bonds can form.',
      zhHant: '粒子必須以足夠的能量和正確的方向碰撞，舊鍵才可能斷裂，新鍵才可能形成。',
    },
    visual: 'particles',
    layout: 'question',
    emphasis: 'energy + orientation',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'collision-1', text: { en: 'First condition: particles collide.', zhHant: '第一個條件：粒子互相碰撞。' } },
      { id: 'collision-2', text: { en: 'Second condition: the collision has enough energy.', zhHant: '第二個條件：碰撞具有足夠能量。' } },
      { id: 'collision-3', text: { en: 'Third condition: the orientation is useful for bond changes.', zhHant: '第三個條件：碰撞方向有助於化學鍵改變。' } },
    ],
    teacherNote: 'Ask students to mime a weak bump and a useful bump with hands. Watch for the misconception that every collision causes a reaction.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-reactions-activation-definition',
    title: { en: 'Activation energy', zhHant: '活化能' },
    body: {
      en: 'Activation energy is the minimum energy needed for reacting particles to form products.',
      zhHant: '活化能是反應粒子形成生成物所需要的最低能量。',
    },
    visual: 'graph',
    layout: 'concept',
    emphasis: 'minimum energy for products',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'activation-definition-1', text: { en: 'Reactants begin with stored chemical energy.', zhHant: '反應物一開始具有儲存的化學能。' } },
      { id: 'activation-definition-2', text: { en: 'They must reach the energy barrier.', zhHant: '它們必須達到能量障礙。' } },
      { id: 'activation-definition-3', text: { en: 'After the barrier, products can form.', zhHant: '越過障礙後，生成物才可以形成。' } },
    ],
    teacherNote: 'Define activation energy only after students have named the need for enough energy. Point to "minimum" and ask what happens below that level.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-reactions-energy-profile',
    title: { en: 'Reading the reaction profile', zhHant: '讀懂反應能量圖' },
    body: {
      en: 'A reaction profile shows reactants, the activation-energy barrier, and products.',
      zhHant: '反應能量圖顯示反應物、活化能障礙和生成物。',
    },
    visual: 'graph',
    layout: 'diagram',
    emphasis: 'reactants -> barrier -> products',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'profile-1', text: { en: 'Start: reactants', zhHant: '起點：反應物' } },
      { id: 'profile-2', text: { en: 'Peak: activation-energy barrier', zhHant: '最高點：活化能障礙' } },
      { id: 'profile-3', text: { en: 'End: products', zhHant: '終點：生成物' } },
      { id: 'profile-4', text: { en: 'The higher the barrier, the harder the reaction is to start.', zhHant: '障礙越高，反應越難開始。' } },
    ],
    teacherNote: 'Trace the curve slowly from left to right. Students should say reactants, barrier, products before writing.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-reactions-catalyst-pathway',
    title: { en: 'What does a catalyst change?', zhHant: '催化劑改變了什麼？' },
    body: {
      en: 'A catalyst provides a different reaction pathway with lower activation energy.',
      zhHant: '催化劑提供一條具有較低活化能的不同反應途徑。',
    },
    visual: 'experiment',
    layout: 'comparison',
    emphasis: 'lower activation energy',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'catalyst-pathway-1', text: { en: 'Without catalyst: higher energy barrier', zhHant: '沒有催化劑：能量障礙較高' } },
      { id: 'catalyst-pathway-2', text: { en: 'With catalyst: lower energy barrier', zhHant: '有催化劑：能量障礙較低' } },
      { id: 'catalyst-pathway-3', text: { en: 'More particles can react successfully each second.', zhHant: '每秒有更多粒子能成功反應。' } },
      { id: 'catalyst-pathway-4', text: { en: 'The products are still the same chemical target.', zhHant: '生成物仍然是相同的化學目標。' } },
    ],
    teacherNote: 'Emphasise pathway, not magic. A catalyst does not give unlimited energy; it lowers the barrier for a different route.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-reactions-catalyst-not-used',
    title: { en: 'A catalyst is not used up', zhHant: '催化劑不會被消耗' },
    body: {
      en: 'A catalyst helps the reaction happen faster, but it is not consumed by the overall reaction.',
      zhHant: '催化劑幫助反應更快發生，但在整個反應中不會被消耗。',
    },
    visual: 'experiment',
    layout: 'diagram',
    emphasis: 'helps, then remains',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'catalyst-cycle-1', text: { en: 'Reactants attach or interact.', zhHant: '反應物附著或互相作用。' } },
      { id: 'catalyst-cycle-2', text: { en: 'Products form more easily.', zhHant: '生成物較容易形成。' } },
      { id: 'catalyst-cycle-3', text: { en: 'The catalyst is available again.', zhHant: '催化劑又可以再次使用。' } },
    ],
    teacherNote: 'Ask: if the catalyst is still available, why can a small amount help many particles? Expected idea: it can be reused.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-reactions-rate-check',
    title: { en: 'Explain the rate change', zhHant: '解釋反應速率改變' },
    body: {
      en: 'If activation energy becomes lower, more particle collisions have enough energy to react successfully.',
      zhHant: '如果活化能降低，就會有更多粒子碰撞具有足夠能量並成功反應。',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'more successful collisions',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'rate-check-1', text: { en: 'Prediction: Will the reaction rate increase or decrease?', zhHant: '預測：反應速率會增加還是降低？' } },
      { id: 'rate-check-2', text: { en: 'Answer: increase.', zhHant: '答案：增加。' } },
      { id: 'rate-check-3', text: { en: 'Reason: more collisions reach the lower energy barrier.', zhHant: '原因：更多碰撞能達到較低的能量障礙。' } },
    ],
    teacherNote: 'Give 30 seconds of quiet writing before revealing the answer. Require the words activation energy and successful collision.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-reactions-exit',
    title: { en: 'Exit check: one complete explanation', zhHant: '課堂檢核：完整解釋一句話' },
    body: {
      en: 'Use activation energy, catalyst, and successful collision in one scientific explanation.',
      zhHant: '使用「活化能」、「催化劑」和「成功碰撞」寫出一句科學解釋。',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'use all three terms',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'activation-exit-1', text: { en: 'A catalyst lowers activation energy.', zhHant: '催化劑降低活化能。' } },
      { id: 'activation-exit-2', text: { en: 'More collisions become successful.', zhHant: '更多碰撞會變成成功碰撞。' } },
      { id: 'activation-exit-3', text: { en: 'Therefore the reaction rate increases.', zhHant: '因此反應速率增加。' } },
    ],
    teacherNote: 'Use this as the written exit ticket. Students can combine the three reveal points into one sentence.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
]

const endoExothermicSlides: LessonSlide[] = [
  {
    id: 'j1-ch2-energy-change-title',
    title: { en: 'Endothermic and exothermic reactions', zhHant: '吸熱反應與放熱反應' },
    body: {
      en: 'Chemical reactions can transfer energy into or out of the reaction system.',
      zhHant: '化學反應可以讓能量進入或離開反應系統。',
    },
    visual: 'experiment',
    layout: 'hero',
    emphasis: 'energy moves',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'energy-title-1', text: { en: 'Hand warmer: energy leaves the reaction system.', zhHant: '暖暖包：能量離開反應系統。' } },
      { id: 'energy-title-2', text: { en: 'Cold pack: energy enters the reaction system.', zhHant: '冰敷包：能量進入反應系統。' } },
    ],
    teacherNote: 'Use familiar examples first. Do not define endothermic/exothermic until students have noticed energy direction.',
    sourceId: 'src-j1-ch2-reactions-ppt',
  },
  {
    id: 'j1-ch2-energy-system-surroundings',
    title: { en: 'System and surroundings', zhHant: '系統與周圍環境' },
    body: {
      en: 'The system is the chemicals reacting. The surroundings are everything around the reaction, including the container, air, and your hand.',
      zhHant: '系統是正在反應的化學物質。周圍環境是反應周圍的一切，包括容器、空氣和你的手。',
    },
    visual: 'particles',
    layout: 'concept',
    emphasis: 'track energy direction',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'system-1', text: { en: 'System: reacting chemicals', zhHant: '系統：正在反應的化學物質' } },
      { id: 'system-2', text: { en: 'Surroundings: container, air, hand, thermometer', zhHant: '周圍環境：容器、空氣、手、溫度計' } },
      { id: 'system-3', text: { en: 'Question: Which way does energy move?', zhHant: '問題：能量往哪個方向移動？' } },
    ],
    teacherNote: 'Draw a box for the system. Arrows should cross the box boundary; this prevents students from saying simply "it gets hot" without naming energy direction.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-exothermic',
    title: { en: 'Exothermic reactions release energy', zhHant: '放熱反應釋放能量' },
    body: {
      en: 'In an exothermic reaction, energy is transferred from the system to the surroundings. The surroundings often become warmer.',
      zhHant: '在放熱反應中，能量從系統傳到周圍環境。周圍環境通常會變暖。',
    },
    visual: 'graph',
    layout: 'diagram',
    emphasis: 'energy leaves the system',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'exo-1', text: { en: 'Energy arrow: system -> surroundings', zhHant: '能量箭頭：系統 → 周圍環境' } },
      { id: 'exo-2', text: { en: 'Temperature around the reaction may rise.', zhHant: '反應周圍的溫度可能上升。' } },
      { id: 'exo-3', text: { en: 'Products have less stored energy than reactants.', zhHant: '生成物儲存的能量比反應物少。' } },
    ],
    teacherNote: 'Students often say "the reaction is hot." Reframe it: energy leaves the reacting chemicals and warms the surroundings.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-endothermic',
    title: { en: 'Endothermic reactions absorb energy', zhHant: '吸熱反應吸收能量' },
    body: {
      en: 'In an endothermic reaction, energy is transferred from the surroundings into the system. The surroundings often become cooler.',
      zhHant: '在吸熱反應中，能量從周圍環境傳入系統。周圍環境通常會變冷。',
    },
    visual: 'graph',
    layout: 'diagram',
    emphasis: 'energy enters the system',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'endo-1', text: { en: 'Energy arrow: surroundings -> system', zhHant: '能量箭頭：周圍環境 → 系統' } },
      { id: 'endo-2', text: { en: 'Temperature around the reaction may fall.', zhHant: '反應周圍的溫度可能下降。' } },
      { id: 'endo-3', text: { en: 'Products have more stored energy than reactants.', zhHant: '生成物儲存的能量比反應物多。' } },
    ],
    teacherNote: 'Connect to a cold pack. The pack feels cold because energy is taken from the surroundings into the reaction system.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-energy-profile-compare',
    title: { en: 'Compare energy profiles', zhHant: '比較能量圖' },
    body: {
      en: 'Use the height of products compared with reactants to decide whether the reaction is exothermic or endothermic.',
      zhHant: '比較生成物與反應物的高度，判斷反應是放熱還是吸熱。',
    },
    visual: 'graph',
    layout: 'comparison',
    emphasis: 'products lower or higher?',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'profiles-1', text: { en: 'Products lower than reactants: exothermic', zhHant: '生成物比反應物低：放熱反應' } },
      { id: 'profiles-2', text: { en: 'Products higher than reactants: endothermic', zhHant: '生成物比反應物高：吸熱反應' } },
      { id: 'profiles-3', text: { en: 'Both still need activation energy to start.', zhHant: '兩者仍然都需要活化能才會開始。' } },
    ],
    teacherNote: 'Bring back Lesson 1: both profiles still have an activation-energy barrier. The end height tells the energy-change type.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-classify-examples',
    title: { en: 'Classify the examples', zhHant: '分類例子' },
    body: {
      en: 'Decide whether each example shows energy leaving the system or entering the system.',
      zhHant: '判斷每個例子顯示能量離開系統，還是進入系統。',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'use energy direction',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'classify-1', text: { en: 'Hand warmer: exothermic - energy leaves the system.', zhHant: '暖暖包：放熱反應 — 能量離開系統。' } },
      { id: 'classify-2', text: { en: 'Instant cold pack: endothermic - energy enters the system.', zhHant: '即用冰敷包：吸熱反應 — 能量進入系統。' } },
      { id: 'classify-3', text: { en: 'If the surroundings warm up, the reaction is usually exothermic.', zhHant: '如果周圍環境變暖，反應通常是放熱反應。' } },
      { id: 'classify-4', text: { en: 'If the surroundings cool down, the reaction is usually endothermic.', zhHant: '如果周圍環境變冷，反應通常是吸熱反應。' } },
    ],
    teacherNote: 'Ask students to justify with arrows, not just labels. Expected language: energy moves from/to the system.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-energy-graph-question',
    title: { en: 'Graph check', zhHant: '圖表檢核' },
    body: {
      en: 'A graph ends with products lower than reactants. What type of reaction is it, and how do you know?',
      zhHant: '一張圖中，生成物的位置比反應物低。這是哪一種反應？你怎麼知道？',
    },
    visual: 'graph',
    layout: 'question',
    emphasis: 'products lower than reactants',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'graph-check-1', text: { en: 'Type: exothermic reaction.', zhHant: '種類：放熱反應。' } },
      { id: 'graph-check-2', text: { en: 'Evidence: products have less stored energy.', zhHant: '證據：生成物儲存的能量較少。' } },
      { id: 'graph-check-3', text: { en: 'Energy has been transferred to the surroundings.', zhHant: '能量已經傳到周圍環境。' } },
    ],
    teacherNote: 'This is the representative reveal check. Let students answer before showing the type, then require evidence from the graph.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
  {
    id: 'j1-ch2-energy-exit',
    title: { en: 'Exit check: choose the evidence', zhHant: '課堂檢核：選擇證據' },
    body: {
      en: 'Explain the difference between exothermic and endothermic reactions using system, surroundings, and energy transfer.',
      zhHant: '使用「系統」、「周圍環境」和「能量轉移」解釋放熱反應與吸熱反應的差異。',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'system + surroundings + energy',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'energy-exit-1', text: { en: 'Exothermic: energy leaves the system.', zhHant: '放熱：能量離開系統。' } },
      { id: 'energy-exit-2', text: { en: 'Endothermic: energy enters the system.', zhHant: '吸熱：能量進入系統。' } },
      { id: 'energy-exit-3', text: { en: 'Use temperature change as evidence from the surroundings.', zhHant: '使用周圍環境的溫度變化作為證據。' } },
    ],
    teacherNote: 'Collect a two-column comparison. Strong responses name the direction of energy transfer and one observable temperature clue.',
    sourceId: 'src-j1-ch2-reactions-pilot',
  },
]

export const j1PilotLessons: ScienceLesson[] = [
  {
    id: 'activation-energy-catalysts',
    unitId: 'j1-fall-reactions',
    title: 'Activation Energy and Catalysts',
    subtitle: 'Why reactions need a starting push and how catalysts lower the energy barrier',
    year: 'J1',
    semester: 'Fall',
    chapter: 'Ch.2 Reactions',
    lessonOrder: 10,
    duration: 50,
    status: 'Published',
    updated: '13 August 2026',
    objectives: [
      'Describe the energy and orientation conditions needed for a successful particle collision.',
      'Define activation energy as the minimum energy needed for reactants to form products.',
      'Read a simple reaction-profile graph by identifying reactants, activation-energy barrier, and products.',
      'Explain how a catalyst lowers activation energy and increases reaction rate without being used up.',
    ],
    sourceReferences: j1ReactionSources,
    slides: activationEnergySlides,
    resources: reactionResources,
  },
  {
    id: 'endo-exothermic',
    unitId: 'j1-fall-reactions',
    title: 'Endothermic and Exothermic Reactions',
    subtitle: 'Using energy-transfer direction and reaction profiles to classify reactions',
    year: 'J1',
    semester: 'Fall',
    chapter: 'Ch.2 Reactions',
    lessonOrder: 11,
    duration: 50,
    status: 'Published',
    updated: '13 August 2026',
    objectives: [
      'Identify the reaction system and its surroundings.',
      'Describe exothermic reactions as energy transfer from the system to the surroundings.',
      'Describe endothermic reactions as energy transfer from the surroundings into the system.',
      'Use product and reactant energy levels on a reaction profile to classify energy-change reactions.',
    ],
    sourceReferences: j1ReactionSources,
    slides: endoExothermicSlides,
    resources: reactionResources,
  },
  {
    id: 'concentration-solubility',
    unitId: 'j1-spring-solutions',
    title: 'Concentration and Solubility',
    subtitle: 'From dissolved particles to interpreting solubility curves',
    year: 'J1',
    semester: 'Spring / Summer',
    chapter: 'Ch.3.1',
    lessonOrder: 1,
    duration: 100,
    status: 'Published',
    updated: '8 July 2026',
    objectives: ['Describe concentration.', 'Explain saturation.', 'Read values from a solubility curve.'],
    sourceReferences: [
      {
        id: 'src-j1-ppt',
        type: 'presentation',
        title: 'Copy of J1 PPT.pptx',
        location: 'Google Drive / J1Science',
        notes: 'Authoritative J1 slide source. Slide ranges still need to be mapped before real pilot ingestion.',
      },
    ],
    slides: [
      {
        id: 'solution-1',
        title: { en: 'What is concentration?', zhHant: '什麼是濃度？' },
        body: {
          en: 'Concentration describes how much solute is dissolved in a particular volume of solution.',
          zhHant: '濃度描述在特定體積的溶液中溶解了多少溶質。',
        },
        visual: 'particles',
        teacherNote: 'Use two cups with equal volume but different drink-powder amounts as a visual comparison.',
        sourceId: 'src-j1-ppt',
      },
      {
        id: 'solution-2',
        title: { en: 'Reading a solubility curve', zhHant: '閱讀溶解度曲線' },
        body: {
          en: 'The curve shows the maximum mass of solute that dissolves at each temperature.',
          zhHant: '曲線顯示在每個溫度下可溶解的最大溶質質量。',
        },
        visual: 'graph',
        revealMode: 'step-by-step',
        reveals: [
          { id: 'solution-2-a', text: { en: 'Choose the temperature on the x-axis.', zhHant: '在 x 軸選擇溫度。' } },
          { id: 'solution-2-b', text: { en: 'Move up to the curve.', zhHant: '向上移動到曲線。' } },
          { id: 'solution-2-c', text: { en: 'Read the mass on the y-axis.', zhHant: '在 y 軸讀取質量。' } },
        ],
        teacherNote: 'Model one reading slowly: choose temperature, move vertically to the curve, then horizontally to mass.',
        sourceId: 'src-j1-ppt',
      },
      {
        id: 'solution-3',
        title: { en: 'Saturated or unsaturated?', zhHant: '飽和還是不飽和？' },
        body: {
          en: 'A saturated solution contains the maximum amount of dissolved solute at that temperature.',
          zhHant: '飽和溶液在該溫度下含有最大量的已溶解溶質。',
        },
        visual: 'experiment',
        teacherNote: 'Ask what evidence would show that no more solute can dissolve.',
        sourceId: 'src-j1-ppt',
      },
    ],
    resources: [
      { id: 'r6', title: 'Solubility-curve practice', type: 'Worksheet', format: 'PDF', detail: 'PDF - 3 pages', sourceId: 'src-j1-ppt' },
      { id: 'r7', title: 'Solubility review quiz', type: 'Quiz', format: 'Google Forms', detail: 'Editable - 10 questions', sourceId: 'src-j1-ppt' },
    ],
  },
]
