#!/usr/bin/env node
import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { basename, join, resolve } from 'node:path'
import { spawnSync } from 'node:child_process'

const [, , inputArg, outputArg] = process.argv

if (!inputArg) {
  console.error('Usage: node scripts/science-lessons/extract-pptx.mjs <source.pptx> [output-dir]')
  process.exit(1)
}

const input = resolve(inputArg)
const output = resolve(outputArg ?? `science-pptx-extract/${basename(input, '.pptx')}`)
const scratch = join(output, '.pptx-expanded')
const mediaOutput = join(output, 'media')

if (!existsSync(input)) {
  console.error(`PPTX not found: ${input}`)
  process.exit(1)
}

rmSync(output, { recursive: true, force: true })
mkdirSync(output, { recursive: true })
mkdirSync(mediaOutput, { recursive: true })

const tar = spawnSync('tar', ['-xf', input, '-C', output], { encoding: 'utf8' })
if (tar.status !== 0) {
  console.error(tar.stderr || tar.stdout || 'Unable to expand PPTX with tar.')
  console.error('A PPTX is a zip archive. Install a zip tool or extract it manually, then rerun from the expanded folder.')
  process.exit(tar.status ?? 1)
}

mkdirSync(scratch, { recursive: true })
for (const entry of ['ppt', '[Content_Types].xml', '_rels', 'docProps']) {
  const source = join(output, entry)
  if (existsSync(source)) cpSync(source, join(scratch, entry), { recursive: true })
}

const mediaDir = join(output, 'ppt', 'media')
if (existsSync(mediaDir)) {
  cpSync(mediaDir, mediaOutput, { recursive: true })
}

const slideDir = join(output, 'ppt', 'slides')
const slideFiles = existsSync(slideDir)
  ? Array.from({ length: 500 }, (_, index) => `slide${index + 1}.xml`).filter((name) => existsSync(join(slideDir, name)))
  : []

const slides = slideFiles.map((name, index) => {
  const xml = readFileSync(join(slideDir, name), 'utf8')
  const text = Array.from(xml.matchAll(/<a:t>(.*?)<\/a:t>/g), (match) => decodeXml(match[1])).filter(Boolean)
  const relPath = join(slideDir, '_rels', `${name}.rels`)
  const relXml = existsSync(relPath) ? readFileSync(relPath, 'utf8') : ''
  const images = Array.from(relXml.matchAll(/Target="\.\.\/media\/([^"]+)"/g), (match) => ({
    file: match[1],
    extractedPath: `media/${match[1]}`,
  }))

  return {
    slideNumber: index + 1,
    sourceXml: `ppt/slides/${name}`,
    text,
    images,
  }
})

const manifest = {
  sourceFile: input,
  extractedAt: new Date().toISOString(),
  slideCount: slides.length,
  mediaDirectory: 'media',
  slides,
}

writeFileSync(join(output, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`)
writeFileSync(join(output, 'README.md'), [
  `# PPTX Extract: ${basename(input)}`,
  '',
  'This folder is generated by `scripts/science-lessons/extract-pptx.mjs`.',
  '',
  '- `manifest.json` preserves slide order, extracted text, and image references.',
  '- `media/` contains embedded PPTX image files copied from `ppt/media`.',
  '- Use slide numbers from the manifest as `originalSlideRef` in Science visual metadata.',
  '',
].join('\n'))

copyFileSync(input, join(output, basename(input)))
rmSync(join(output, 'ppt'), { recursive: true, force: true })
rmSync(join(output, '[Content_Types].xml'), { force: true })
rmSync(join(output, '_rels'), { recursive: true, force: true })
rmSync(join(output, 'docProps'), { recursive: true, force: true })

console.log(`Extracted ${slides.length} slides to ${output}`)

function decodeXml(value) {
  return value
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .trim()
}
