import type { LessonSlide, ScienceLesson } from '../../types/lesson'

const driveUrl = (id: string) => `https://drive.google.com/file/d/${id}/view`

const atomModelSvg = `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1200 800'><rect width='1200' height='800' fill='rgb(8,18,48)'/><circle cx='600' cy='400' r='330' fill='none' stroke='rgb(93,188,252)' stroke-width='7' opacity='.55'/><circle cx='600' cy='400' r='245' fill='none' stroke='rgb(112,235,198)' stroke-width='5' opacity='.45'/><ellipse cx='600' cy='400' rx='390' ry='120' fill='none' stroke='rgb(147,197,253)' stroke-width='8' opacity='.65' transform='rotate(-25 600 400)'/><ellipse cx='600' cy='400' rx='390' ry='120' fill='none' stroke='rgb(45,212,191)' stroke-width='8' opacity='.55' transform='rotate(25 600 400)'/><circle cx='600' cy='400' r='82' fill='rgb(250,204,21)'/><circle cx='570' cy='390' r='30' fill='rgb(248,113,113)'/><circle cx='628' cy='418' r='30' fill='rgb(96,165,250)'/><circle cx='612' cy='365' r='25' fill='rgb(248,113,113)'/><circle cx='374' cy='251' r='24' fill='rgb(125,211,252)'/><circle cx='812' cy='548' r='24' fill='rgb(125,211,252)'/><circle cx='870' cy='270' r='24' fill='rgb(125,211,252)'/><text x='80' y='105' fill='white' font-family='Arial' font-size='54' font-weight='700'>Modern atom model</text><text x='80' y='168' fill='rgb(203,213,225)' font-family='Arial' font-size='30'>nucleus, protons, neutrons, electron cloud</text><text x='704' y='400' fill='white' font-family='Arial' font-size='32' font-weight='700'>nucleus</text><text x='915' y='270' fill='rgb(191,219,254)' font-family='Arial' font-size='30'>electron</text></svg>`

const matterSvg = `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1200 800'><defs><radialGradient id='g' cx='45%' cy='30%'><stop offset='0%' stop-color='rgb(186,230,253)'/><stop offset='70%' stop-color='rgb(14,116,144)'/><stop offset='100%' stop-color='rgb(8,47,73)'/></radialGradient></defs><rect width='1200' height='800' fill='rgb(5,19,40)'/><circle cx='610' cy='405' r='260' fill='url(%23g)'/><g fill='rgb(255,255,255)' opacity='.88'><circle cx='522' cy='320' r='20'/><circle cx='585' cy='352' r='16'/><circle cx='648' cy='307' r='20'/><circle cx='704' cy='380' r='16'/><circle cx='555' cy='460' r='18'/><circle cx='640' cy='500' r='22'/><circle cx='740' cy='470' r='14'/></g><text x='72' y='120' fill='white' font-family='Arial' font-size='58' font-weight='700'>Matter zoom</text><text x='72' y='186' fill='rgb(203,213,225)' font-family='Arial' font-size='32'>everything around us is made from particles</text><text x='820' y='620' fill='rgb(191,219,254)' font-family='Arial' font-size='34'>droplet → particles → atoms</text></svg>`

const timelineSvg = `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1200 800'><rect width='1200' height='800' fill='rgb(15,23,42)'/><line x1='130' y1='410' x2='1070' y2='410' stroke='rgb(148,163,184)' stroke-width='8'/><g font-family='Arial'><text x='75' y='120' fill='white' font-size='58' font-weight='700'>Atomic models changed</text><text x='75' y='184' fill='rgb(203,213,225)' font-size='32'>new evidence improved the model over time</text></g><g font-family='Arial' font-size='28' text-anchor='middle'><circle cx='160' cy='410' r='44' fill='rgb(59,130,246)'/><text x='160' y='420' fill='white' font-weight='700'>1</text><text x='160' y='505' fill='white'>Democritus</text><text x='160' y='545' fill='rgb(203,213,225)' font-size='24'>tiny pieces</text><circle cx='330' cy='410' r='44' fill='rgb(34,197,94)'/><text x='330' y='420' fill='white' font-weight='700'>2</text><text x='330' y='505' fill='white'>Dalton</text><text x='330' y='545' fill='rgb(203,213,225)' font-size='24'>atomic theory</text><circle cx='500' cy='410' r='44' fill='rgb(14,165,233)'/><text x='500' y='420' fill='white' font-weight='700'>3</text><text x='500' y='505' fill='white'>Thomson</text><text x='500' y='545' fill='rgb(203,213,225)' font-size='24'>electrons</text><circle cx='670' cy='410' r='44' fill='rgb(234,179,8)'/><text x='670' y='420' fill='white' font-weight='700'>4</text><text x='670' y='505' fill='white'>Rutherford</text><text x='670' y='545' fill='rgb(203,213,225)' font-size='24'>nucleus</text><circle cx='840' cy='410' r='44' fill='rgb(168,85,247)'/><text x='840' y='420' fill='white' font-weight='700'>5</text><text x='840' y='505' fill='white'>Bohr</text><text x='840' y='545' fill='rgb(203,213,225)' font-size='24'>energy levels</text><circle cx='1010' cy='410' r='44' fill='rgb(239,68,68)'/><text x='1010' y='420' fill='white' font-weight='700'>6</text><text x='1010' y='505' fill='white'>Chadwick</text><text x='1010' y='545' fill='rgb(203,213,225)' font-size='24'>neutrons</text></g></svg>`

const sourceReferences = [
  {
    id: 'src-j2-opening-source-ppt',
    type: 'presentation' as const,
    title: 'J2 PPT (updated).pptx',
    location: 'Google Drive / J2Science',
    driveFileId: '14AUxNBq96_rRR9exiieSsHBdvuth4ofh',
    url: 'https://docs.google.com/presentation/d/14AUxNBq96_rRR9exiieSsHBdvuth4ofh/edit',
    slideRange: 'Source slides 1-15: Chapter 1, Section 1 — Elements and Atoms, from matter through the modern atomic model',
    notes:
      'Authoritative J2 source deck. This lesson preserves the original fifteen-slide opening sequence instead of compressing or replacing it.',
  },
  {
    id: 'src-j2-opening-pptx-v2',
    type: 'presentation' as const,
    title: 'Previous J2 editable PPT draft',
    location: 'Google Drive generated draft',
    driveFileId: '1WikGkibvBob-Crp2AHiKsFaKnza22kcB',
    url: 'https://docs.google.com/presentation/d/1WikGkibvBob-Crp2AHiKsFaKnza22kcB/edit',
    notes:
      'Earlier compressed draft retained only for audit. It is not the source of truth or the teaching standard.',
  },
]

const resources = [
  {
    id: 'j2-opening-source-ppt',
    title: 'Source PPT: J2 PPT (updated).pptx',
    type: 'Presentation' as const,
    format: 'PPTX' as const,
    detail: 'Drive source for Chapter 1 Section 1 opening',
    href: 'https://docs.google.com/presentation/d/14AUxNBq96_rRR9exiieSsHBdvuth4ofh/edit',
    driveFileId: '14AUxNBq96_rRR9exiieSsHBdvuth4ofh',
    sourceId: 'src-j2-opening-source-ppt',
    teacherOnly: true,
  },
  {
    id: 'j2-opening-editable-pptx',
    title: 'Previous editable PPT draft: not the teaching standard',
    type: 'Presentation' as const,
    format: 'PPTX' as const,
    detail: 'Earlier compressed draft kept only for audit; rebuild the editable teaching version from the exact source sequence',
    href: driveUrl('1WikGkibvBob-Crp2AHiKsFaKnza22kcB'),
    driveFileId: '1WikGkibvBob-Crp2AHiKsFaKnza22kcB',
    sourceId: 'src-j2-opening-pptx-v2',
    teacherOnly: true,
  },
]

const slides: LessonSlide[] = [
  {
    id: 'j2-ch1-title',
    title: { en: 'Chapter 1: ATOMS AND BONDING', zhHant: '第一章：原子與鍵結' },
    body: { en: 'BY: XG LAWRENCE', zhHant: '作者：XG LAWRENCE' },
    visual: 'particles',
    layout: 'hero',
    emphasis: 'atoms and bonding',
    media: { type: 'image', title: 'Modern atom model', src: atomModelSvg, alt: 'Modern atom model with nucleus and electron cloud' },
    teacherNote: 'Source slide 1. Preserve the chapter opener before Section 1 begins.',
    sourceId: 'src-j2-opening-source-ppt',
  },
  {
    id: 'j2-ch1-1-title',
    title: { en: 'Chapter 1: Section 1', zhHant: '第一章：第一節' },
    body: { en: 'Elements and Atoms', zhHant: '元素與原子' },
    visual: 'particles',
    layout: 'hero',
    emphasis: 'elements and atoms',
    media: { type: 'image', title: 'Matter zoom model', src: matterSvg, alt: 'Matter zooming into particles and atoms' },
    teacherNote: 'Source slide 2. Section title: Elements and Atoms.',
    sourceId: 'src-j2-opening-source-ppt',
  },
  {
    id: 'j2-ch1-1-question-building-blocks',
    title: { en: 'QUESTION OF THE DAY!!', zhHant: '今日問題！' },
    body: { en: 'Why are elements sometimes called the building blocks of matter?', zhHant: '為什麼元素有時被稱為物質的基本組成單位？' },
    visual: 'question',
    layout: 'question',
    emphasis: 'building blocks of matter',
    teacherNote: 'Source slide 3. Ask the question before giving the definitions.',
    sourceId: 'src-j2-opening-source-ppt',
  },
  {
    id: 'j2-ch1-1-building-blocks-matter',
    title: { en: 'The Building Blocks of Matter', zhHant: '物質的基本組成單位' },
    body: { en: 'Matter is anything that has mass and takes up space.', zhHant: '物質是任何有質量並佔有空間的東西。' },
    visual: 'particles',
    layout: 'image-focus',
    emphasis: 'matter + elements',
    media: { type: 'image', title: 'Matter particle model', src: matterSvg, alt: 'Matter represented as particles' },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'j2-s4-elements', text: { en: 'Elements are the simplest pure substances.', zhHant: '元素是最簡單的純物質。' } },
      { id: 'j2-s4-building-blocks', text: { en: 'Elements are called the building blocks of matter because all matter is composed of one element or a combination of elements.', zhHant: '元素被稱為物質的基本組成單位，因為所有物質都是由一種元素或多種元素的組合構成。' } },
    ],
    teacherNote: 'Source slide 4. Keep the three source statements in this order.',
    sourceId: 'src-j2-opening-source-ppt',
  },
  {
    id: 'j2-ch1-1-elements-compounds-mixtures',
    title: { en: 'The Building Blocks of Matter', zhHant: '物質的基本組成單位' },
    body: { en: 'ELEMENTS, COMPOUNDS, AND MIXTURES', zhHant: '元素、化合物與混合物' },
    visual: 'particles',
    layout: 'comparison',
    emphasis: 'compound + mixture',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'j2-s5-compound', text: { en: 'A pure substance made of two or more elements that are combined chemically in a specific ratio is called a compound.', zhHant: '由兩種或更多元素以特定比例化學結合而成的純物質稱為化合物。' } },
      { id: 'j2-s5-mixture', text: { en: 'Two or more substances that are in the same place but are not chemically combined is a mixture.', zhHant: '兩種或更多物質位於同一處但沒有化學結合，稱為混合物。' } },
    ],
    teacherNote: 'Source slide 5. Contrast chemically combined compounds with mixtures that are not chemically combined.',
    sourceId: 'src-j2-opening-source-ppt',
  },
  {
    id: 'j2-ch1-1-particles-elements',
    title: { en: 'The Building Blocks of Matter', zhHant: '物質的基本組成單位' },
    body: { en: 'PARTICLES OF ELEMENTS', zhHant: '元素的粒子' },
    visual: 'particles',
    layout: 'image-focus',
    emphasis: 'atom + atomos',
    media: { type: 'image', title: 'Atom model', src: atomModelSvg, alt: 'Atom model representing a very small particle' },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'j2-s6-atom', text: { en: 'An atom is the smallest particle of an element.', zhHant: '原子是元素中最小的粒子。' } },
      { id: 'j2-s6-democritus', text: { en: 'Democritus proposed the idea that matter is formed of small pieces that could not be cut into smaller parts; it was called atomos.', zhHant: '德謨克利特提出物質由無法再切分的微小部分組成，這些部分被稱為 atomos。' } },
    ],
    teacherNote: 'Source slide 6. Introduce atom only after matter, elements, compounds and mixtures.',
    sourceId: 'src-j2-opening-source-ppt',
  },
  {
    id: 'j2-ch1-1-question-theory',
    title: { en: 'QUESTION OF THE DAY!!', zhHant: '今日問題！' },
    body: { en: 'How did the atomic theory develop and change?', zhHant: '原子理論是如何發展與改變的？' },
    visual: 'question',
    layout: 'question',
    emphasis: 'atomic theory development',
    media: { type: 'image', title: 'Atomic theory timeline', src: timelineSvg, alt: 'Timeline showing changes in atomic models' },
    teacherNote: 'Source slide 7. This question starts the atomic-model sequence.',
    sourceId: 'src-j2-opening-source-ppt',
  },
  {
    id: 'j2-ch1-1-theory-models',
    title: { en: 'Atomic Theory and Models', zhHant: '原子理論與模型' },
    body: { en: 'A scientific theory is a well-tested idea that explains and connects a wide range of observations.', zhHant: '科學理論是經過充分測試、能解釋並連結廣泛觀察結果的想法。' },
    visual: 'particles',
    layout: 'diagram',
    emphasis: 'scientific theory + models',
    media: { type: 'image', title: 'Atomic theory timeline', src: timelineSvg, alt: 'Atomic-model timeline' },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'j2-s8-models', text: { en: 'Models are physical, mental, visual, and other representations of an idea to help people understand what they cannot see.', zhHant: '模型可以是實體、心理、視覺或其他形式的概念呈現，用來幫助人們理解看不見的事物。' } },
    ],
    teacherNote: 'Source slide 8. Define scientific theory and model before the named scientists.',
    sourceId: 'src-j2-opening-source-ppt',
  },
  {
    id: 'j2-ch1-1-dalton',
    title: { en: 'Atomic Theory and Models', zhHant: '原子理論與模型' },
    body: { en: 'DALTON’S ATOMIC THEORY', zhHant: '道爾頓的原子理論' },
    visual: 'particles',
    layout: 'image-focus',
    emphasis: 'Dalton',
    media: { type: 'image', title: 'Atomic theory timeline', src: timelineSvg, alt: 'Atomic theory timeline highlighting the sequence of models' },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'j2-s9-dalton-proposed', text: { en: 'Dalton proposed the atomic theory and models for the atom.', zhHant: '道爾頓提出了原子理論以及原子的模型。' } },
      { id: 'j2-s9-accepted', text: { en: 'This theory is still accepted today.', zhHant: '這個理論至今仍被接受。' } },
    ],
    teacherNote: 'Source slide 9. Dalton follows the theory/model definitions.',
    sourceId: 'src-j2-opening-source-ppt',
  },
  {
    id: 'j2-ch1-1-thomson',
    title: { en: 'Atomic Theory and Models', zhHant: '原子理論與模型' },
    body: { en: 'THOMSON AND SMALLER PARTS OF ATOMS', zhHant: '湯姆森與原子中的更小粒子' },
    visual: 'particles',
    layout: 'image-focus',
    emphasis: 'electron',
    media: { type: 'image', title: 'Atom model', src: atomModelSvg, alt: 'Atom model showing electrons' },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'j2-s10-smaller', text: { en: 'Thomson proposed that atoms are made up of smaller parts.', zhHant: '湯姆森提出原子是由更小的部分組成。' } },
      { id: 'j2-s10-negative', text: { en: 'He found that atoms contain negatively charged particles.', zhHant: '他發現原子含有帶負電的粒子。' } },
      { id: 'j2-s10-electrons', text: { en: 'These negatively charged particles in atoms became known as electrons.', zhHant: '這些原子中帶負電的粒子後來被稱為電子。' } },
    ],
    teacherNote: 'Source slide 10. The new evidence is the negatively charged electron.',
    sourceId: 'src-j2-opening-source-ppt',
  },
  {
    id: 'j2-ch1-1-rutherford',
    title: { en: 'Atomic Theory and Models', zhHant: '原子理論與模型' },
    body: { en: 'RUTHERFORD AND THE NUCLEUS', zhHant: '拉塞福與原子核' },
    visual: 'particles',
    layout: 'image-focus',
    emphasis: 'nucleus + protons',
    media: { type: 'image', title: 'Atom nucleus model', src: atomModelSvg, alt: 'Atom model showing a small central nucleus' },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'j2-s11-nucleus', text: { en: 'Rutherford proposed that an atom’s positive charge must be clustered in a tiny region in the center called the nucleus.', zhHant: '拉塞福提出原子的正電荷集中在中心一個很小的區域，稱為原子核。' } },
      { id: 'j2-s11-protons', text: { en: 'He named the positively charged particles in the nucleus the protons.', zhHant: '他把原子核中帶正電的粒子命名為質子。' } },
    ],
    teacherNote: 'Source slide 11. Emphasize the tiny central nucleus and positive protons.',
    sourceId: 'src-j2-opening-source-ppt',
  },
  {
    id: 'j2-ch1-1-bohr',
    title: { en: 'Atomic Theory and Models', zhHant: '原子理論與模型' },
    body: { en: 'BOHR’S MODEL', zhHant: '波耳模型' },
    visual: 'particles',
    layout: 'image-focus',
    emphasis: 'specific energy + orbits',
    media: { type: 'image', title: 'Atom model', src: atomModelSvg, alt: 'Atom model with electron paths around the nucleus' },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'j2-s12-bohr', text: { en: 'Bohr proposed that electrons could have only specific amounts of energy, which causes them to move in certain orbits.', zhHant: '波耳提出電子只能具有特定的能量，因此會在特定軌道中移動。' } },
    ],
    teacherNote: 'Source slide 12. Keep this historical Bohr-model claim before the later electron-cloud correction.',
    sourceId: 'src-j2-opening-source-ppt',
  },
  {
    id: 'j2-ch1-1-electron-cloud',
    title: { en: 'Atomic Theory and Models', zhHant: '原子理論與模型' },
    body: { en: 'A CLOUD OF ELECTRONS', zhHant: '電子雲' },
    visual: 'particles',
    layout: 'image-focus',
    emphasis: 'electron cloud + energy level',
    media: { type: 'image', title: 'Modern atom model', src: atomModelSvg, alt: 'Modern atom model representing an electron cloud' },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'j2-s13-cloud', text: { en: 'Scientists later determined that electrons don’t orbit the nucleus, but they can be anywhere in a “cloud” around the nucleus.', zhHant: '科學家後來確定電子不是沿固定軌道繞原子核運行，而是可能出現在原子核周圍的「電子雲」中。' } },
      { id: 'j2-s13-energy', text: { en: 'An electron’s movement is related to its energy level, or the amount of energy it has.', zhHant: '電子的運動與它的能階，也就是它具有的能量多寡有關。' } },
    ],
    teacherNote: 'Source slide 13. Explicitly move from fixed Bohr orbits to the electron-cloud model.',
    sourceId: 'src-j2-opening-source-ppt',
  },
  {
    id: 'j2-ch1-1-modern-model',
    title: { en: 'Atomic Theory and Models', zhHant: '原子理論與模型' },
    body: { en: 'THE MODERN ATOMIC MODEL', zhHant: '現代原子模型' },
    visual: 'particles',
    layout: 'image-focus',
    emphasis: 'Chadwick + neutron',
    media: { type: 'image', title: 'Modern atom model', src: atomModelSvg, alt: 'Modern atom model with protons, neutrons and electrons' },
    revealMode: 'step-by-step',
    reveals: [
      { id: 'j2-s14-chadwick', text: { en: 'Chadwick discovered another particle in the nucleus of atoms.', zhHant: '查兌克在原子核中發現了另一種粒子。' } },
      { id: 'j2-s14-completed', text: { en: 'This discovery completed the modern atomic model.', zhHant: '這項發現完成了現代原子模型。' } },
      { id: 'j2-s14-neutron', text: { en: 'The particle is electrically neutral so it was called a neutron.', zhHant: '這個粒子不帶電，因此被稱為中子。' } },
    ],
    teacherNote: 'Source slide 14. Chadwick and the neutron complete the source sequence of discoveries.',
    sourceId: 'src-j2-opening-source-ppt',
  },
  {
    id: 'j2-ch1-1-models-summary',
    title: { en: 'Atomic Theory and Models', zhHant: '原子理論與模型' },
    body: { en: 'Atomic Theory and Models', zhHant: '原子理論與模型' },
    visual: 'particles',
    layout: 'image-focus',
    emphasis: 'atomic theory and models',
    media: { type: 'image', title: 'Atomic theory timeline', src: timelineSvg, alt: 'Timeline from early atomic ideas to the modern model' },
    teacherNote: 'Source slide 15 contains the Atomic Theory and Models heading/visual. Use it as the visual recap before Section 2.',
    sourceId: 'src-j2-opening-source-ppt',
  },
]

export const j2OpeningLessons: ScienceLesson[] = [
  {
    id: 'j2-ch1-1-elements-atoms-opening',
    unitId: 'j2-fall-atoms-bonding',
    title: 'Chapter 1 · Section 1 — Elements and Atoms',
    subtitle: 'Source slides 1–15: atoms and bonding, elements and atoms, matter, atomic theory and the modern atomic model',
    year: 'J2',
    semester: 'Fall',
    chapter: 'Chapter 1 · Section 1',
    lessonOrder: -10,
    duration: 50,
    status: 'Published',
    updated: '29 August 2026',
    objectives: [
      'Answer why elements are called the building blocks of matter.',
      'Define matter, element, compound, mixture and atom from the source sequence.',
      'Explain scientific theory and models before tracing Dalton, Thomson, Rutherford, Bohr and Chadwick.',
      'Explain electrons, the nucleus, protons, energy levels, the electron cloud and neutrons in source order.',
    ],
    sourceReferences,
    slides,
    resources,
  },
]
