import type { LessonSlide, ScienceLesson } from '../../types/lesson'
import { formatSourceSectionLabel, sourceSectionMappingByUnitId } from '../curriculumSourceMap'

const ecosystemsSectionLabel = formatSourceSectionLabel(sourceSectionMappingByUnitId['j2-fall-ecosystems'])

const j2EcosystemSources = [
  {
    id: 'src-j2-ch2-ecosystems-ppt',
    type: 'presentation' as const,
    title: 'J2 PPT (updated).pptx',
    location: 'Google Drive / J2Science',
    notes:
      'Recovered J2 source presentation for Unit 2 ecosystems. Exact source slide ranges are not yet mapped; this production pass preserves the recovered aquatic habitats, biotic/abiotic factors, food-web change, and interaction sequence without inventing slide numbers.',
  },
  {
    id: 'src-j2-ch2-ecosystems-pilot',
    type: 'manual-entry' as const,
    title: 'Recovered Science Lessons pilot: Aquatic Ecosystems',
    location: 'science-lessons-pilot branch / src/science-lessons/curriculum/j2/pilotLessons.ts',
    notes:
      'Original recovered pilot supplied the lesson title, subtitle, objectives, biotic/abiotic factor definition, food-web change prompt, and resource titles for the worksheet and coastal seas video.',
  },
]

const ecosystemResources = [
  {
    id: 'j2-ch2-ecosystems-source-ppt',
    title: 'Source PPT: J2 PPT (updated).pptx',
    type: 'Presentation' as const,
    format: 'PPTX' as const,
    detail: 'Drive source - J2 Unit 2 ecosystems sequence; exact slide range pending',
    sourceId: 'src-j2-ch2-ecosystems-ppt',
    teacherOnly: true,
  },
  {
    id: 'j2-ch2-aquatic-food-web-challenge',
    title: 'Aquatic food-web challenge',
    type: 'Worksheet' as const,
    format: 'PDF' as const,
    detail: 'Recovered pilot resource - PDF, 2 pages; Drive URL pending',
    sourceId: 'src-j2-ch2-ecosystems-pilot',
  },
  {
    id: 'j2-ch2-coastal-seas-clip',
    title: 'Coastal seas clip',
    type: 'Video' as const,
    format: 'Video' as const,
    detail: 'Recovered pilot resource - 6 min 12 sec; URL pending',
    sourceId: 'src-j2-ch2-ecosystems-pilot',
  },
]

const aquaticHabitatSlides: LessonSlide[] = [
  {
    id: 'j2-ch2-aquatic-title',
    title: { en: 'Aquatic ecosystems', zhHant: '水域生態系' },
    body: {
      en: 'Aquatic ecosystems include freshwater and marine habitats where organisms interact with living and non-living parts of the environment.',
      zhHant: '水域生態系包含淡水和海洋棲地，其中生物會與環境中的生物和非生物部分互動。',
    },
    visual: 'ecosystem',
    layout: 'hero',
    emphasis: 'organisms + environment',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'aquatic-title-1', text: { en: 'Freshwater and marine habitats are both aquatic ecosystems.', zhHant: '淡水和海洋棲地都屬於水域生態系。' } },
      { id: 'aquatic-title-2', text: { en: 'Organisms interact with each other.', zhHant: '生物會彼此互動。' } },
      { id: 'aquatic-title-3', text: { en: 'Organisms also interact with non-living conditions.', zhHant: '生物也會與非生物條件互動。' } },
    ],
    teacherNote: 'Open with a quick image-free prediction: what would a fish need from its habitat besides other living things?',
    sourceId: 'src-j2-ch2-ecosystems-ppt',
  },
  {
    id: 'j2-ch2-ecosystem-system',
    title: { en: 'An ecosystem is a connected system', zhHant: '生態系是一個相互連結的系統' },
    body: {
      en: 'Living organisms interact with each other and with non-living parts of their environment.',
      zhHant: '生物彼此互動，也與環境中的非生物部分互動。',
    },
    visual: 'ecosystem',
    layout: 'concept',
    emphasis: 'biotic + abiotic factors',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'ecosystem-system-1', text: { en: 'Biotic factors are living parts.', zhHant: '生物因子是有生命的部分。' } },
      { id: 'ecosystem-system-2', text: { en: 'Abiotic factors are non-living parts.', zhHant: '非生物因子是沒有生命的部分。' } },
      { id: 'ecosystem-system-3', text: { en: 'Both affect survival and growth.', zhHant: '兩者都會影響生存和生長。' } },
    ],
    teacherNote: 'This preserves the recovered pilot definition. Ask students to give one biotic and one abiotic example before revealing both terms.',
    sourceId: 'src-j2-ch2-ecosystems-pilot',
  },
  {
    id: 'j2-ch2-biotic-abiotic-sort',
    title: { en: 'Sort the habitat factors', zhHant: '分類棲地因子' },
    body: {
      en: 'To understand a habitat, classify the factors as biotic or abiotic, then explain how each one can affect organisms.',
      zhHant: '要了解一個棲地，先把因子分類為生物或非生物，再解釋每一項如何影響生物。',
    },
    visual: 'ecosystem',
    layout: 'comparison',
    emphasis: 'living or non-living?',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'biotic-abiotic-sort-1', text: { en: 'Fish, plants and algae are biotic factors.', zhHant: '魚、水生植物和藻類是生物因子。' } },
      { id: 'biotic-abiotic-sort-2', text: { en: 'Water, light and temperature are abiotic factors.', zhHant: '水、光和溫度是非生物因子。' } },
      { id: 'biotic-abiotic-sort-3', text: { en: 'A useful answer explains the effect, not only the category.', zhHant: '好的答案不只分類，還要解釋影響。' } },
    ],
    teacherNote: 'Prediction first: give students 30 seconds to sort the examples, then reveal the categories and require one effect sentence.',
    sourceId: 'src-j2-ch2-ecosystems-ppt',
  },
  {
    id: 'j2-ch2-freshwater-marine',
    title: { en: 'Freshwater and marine habitats', zhHant: '淡水與海洋棲地' },
    body: {
      en: 'Freshwater and marine habitats have different conditions, so different organisms are suited to each environment.',
      zhHant: '淡水和海洋棲地具有不同條件，因此不同生物適合不同環境。',
    },
    visual: 'ecosystem',
    layout: 'comparison',
    emphasis: 'habitat conditions matter',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'freshwater-marine-1', text: { en: 'Freshwater: rivers, lakes or ponds.', zhHant: '淡水：河流、湖泊或池塘。' } },
      { id: 'freshwater-marine-2', text: { en: 'Marine: seas and oceans.', zhHant: '海洋：海域和海洋。' } },
      { id: 'freshwater-marine-3', text: { en: 'Do not move an organism to a different habitat without checking its needs.', zhHant: '不要未確認需求就把生物移到不同棲地。' } },
    ],
    teacherNote: 'Keep this comparison qualitative because no specific salinity or temperature data is recovered locally.',
    sourceId: 'src-j2-ch2-ecosystems-pilot',
  },
  {
    id: 'j2-ch2-habitat-needs',
    title: { en: 'What makes a habitat suitable?', zhHant: '什麼讓棲地適合生存？' },
    body: {
      en: 'A suitable habitat provides the conditions and resources organisms need to survive and grow.',
      zhHant: '適合的棲地會提供生物生存和生長所需的條件與資源。',
    },
    visual: 'ecosystem',
    layout: 'diagram',
    emphasis: 'survival and growth',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'habitat-needs-1', text: { en: 'Ask: What living things are present?', zhHant: '先問：有哪些生物存在？' } },
      { id: 'habitat-needs-2', text: { en: 'Ask: What non-living conditions are present?', zhHant: '再問：有哪些非生物條件存在？' } },
      { id: 'habitat-needs-3', text: { en: 'Explain how the organism uses or responds to those factors.', zhHant: '解釋生物如何利用或回應這些因子。' } },
    ],
    teacherNote: 'Model the answer stem: "This factor affects the organism because..." Students should avoid listing factors without explanation.',
    sourceId: 'src-j2-ch2-ecosystems-ppt',
  },
  {
    id: 'j2-ch2-interaction-types',
    title: { en: 'Interactions in an ecosystem', zhHant: '生態系中的互動' },
    body: {
      en: 'Organisms can interact by feeding, competing for resources, or depending on conditions in the same habitat.',
      zhHant: '生物可以透過覓食、競爭資源，或依賴同一棲地中的條件而互動。',
    },
    visual: 'ecosystem',
    layout: 'diagram',
    emphasis: 'feeding, resources, conditions',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'interaction-types-1', text: { en: 'Feeding links organisms.', zhHant: '覓食關係會連結生物。' } },
      { id: 'interaction-types-2', text: { en: 'Resource needs can create competition.', zhHant: '資源需求可能造成競爭。' } },
      { id: 'interaction-types-3', text: { en: 'Abiotic conditions can limit where organisms survive.', zhHant: '非生物條件可能限制生物能在哪裡生存。' } },
    ],
    teacherNote: 'Use this as the bridge to the food-web lesson. Ask which interaction could be shown with arrows.',
    sourceId: 'src-j2-ch2-ecosystems-ppt',
  },
  {
    id: 'j2-ch2-habitat-application',
    title: { en: 'Apply it: explain one habitat', zhHant: '應用：解釋一個棲地' },
    body: {
      en: 'Choose an aquatic habitat and explain two biotic factors and two abiotic factors that affect organisms there.',
      zhHant: '選擇一個水域棲地，解釋兩個會影響當地生物的生物因子和兩個非生物因子。',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'classify, then explain',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'habitat-application-1', text: { en: 'Name the habitat.', zhHant: '說出棲地名稱。' } },
      { id: 'habitat-application-2', text: { en: 'Classify four factors.', zhHant: '分類四個因子。' } },
      { id: 'habitat-application-3', text: { en: 'Explain how each factor affects survival or growth.', zhHant: '解釋每個因子如何影響生存或生長。' } },
    ],
    teacherNote: 'Students can answer with freshwater or marine examples. Do not require numbers unless the source worksheet supplies them.',
    sourceId: 'src-j2-ch2-ecosystems-pilot',
  },
  {
    id: 'j2-ch2-habitat-exit',
    title: { en: 'Exit check: use the two key words', zhHant: '課堂檢核：使用兩個關鍵詞' },
    body: {
      en: 'Write one sentence that uses biotic factor and abiotic factor to explain an aquatic ecosystem.',
      zhHant: '寫出一句話，使用「生物因子」和「非生物因子」解釋一個水域生態系。',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'biotic + abiotic',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'habitat-exit-1', text: { en: 'Biotic factor: living part.', zhHant: '生物因子：有生命的部分。' } },
      { id: 'habitat-exit-2', text: { en: 'Abiotic factor: non-living part.', zhHant: '非生物因子：沒有生命的部分。' } },
      { id: 'habitat-exit-3', text: { en: 'Strong answer: explains an effect on organisms.', zhHant: '好的答案：解釋對生物的影響。' } },
    ],
    teacherNote: 'Use this as a quick written check before starting food webs. Require both terms and one effect.',
    sourceId: 'src-j2-ch2-ecosystems-pilot',
  },
]

const aquaticFoodWebSlides: LessonSlide[] = [
  {
    id: 'j2-ch2-food-web-title',
    title: { en: 'Aquatic food webs', zhHant: '水域食物網' },
    body: {
      en: 'Food webs show feeding relationships. A change in one population can affect several other organisms.',
      zhHant: '食物網顯示覓食關係。一個族群的變化可能影響多種其他生物。',
    },
    visual: 'ecosystem',
    layout: 'hero',
    emphasis: 'changes spread through food webs',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'food-web-title-1', text: { en: 'Identify the organisms first.', zhHant: '先辨認生物。' } },
      { id: 'food-web-title-2', text: { en: 'Then trace the feeding links.', zhHant: '再追蹤覓食連結。' } },
      { id: 'food-web-title-3', text: { en: 'Finally predict what changes when one population changes.', zhHant: '最後預測一個族群改變時會發生什麼。' } },
    ],
    teacherNote: 'Preview the recovered worksheet task: students will predict consequences in an aquatic food web.',
    sourceId: 'src-j2-ch2-ecosystems-pilot',
  },
  {
    id: 'j2-ch2-food-chain',
    title: { en: 'Start with one feeding chain', zhHant: '先看一條食物鏈' },
    body: {
      en: 'A feeding chain follows energy and matter from a producer to consumers in a habitat.',
      zhHant: '食物鏈追蹤能量和物質如何從生產者傳到棲地中的消費者。',
    },
    visual: 'ecosystem',
    layout: 'diagram',
    emphasis: 'producer -> consumers',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'food-chain-1', text: { en: 'Producer: makes food using light.', zhHant: '生產者：利用光製造養分。' } },
      { id: 'food-chain-2', text: { en: 'Consumer: gets food by eating organisms.', zhHant: '消費者：藉由吃其他生物獲得食物。' } },
      { id: 'food-chain-3', text: { en: 'Arrow: shows the feeding link.', zhHant: '箭頭：顯示覓食連結。' } },
    ],
    teacherNote: 'The recovered pilot mentions removing a producer. Define producer before using that prediction task.',
    sourceId: 'src-j2-ch2-ecosystems-pilot',
  },
  {
    id: 'j2-ch2-food-web-model',
    title: { en: 'From chain to food web', zhHant: '從食物鏈到食物網' },
    body: {
      en: 'A food web has many feeding links, so one organism can be connected to more than one other organism.',
      zhHant: '食物網有許多覓食連結，因此一種生物可以和多種其他生物相連。',
    },
    visual: 'ecosystem',
    layout: 'concept',
    emphasis: 'many feeding links',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'food-web-model-1', text: { en: 'One chain shows one path.', zhHant: '一條食物鏈顯示一條路徑。' } },
      { id: 'food-web-model-2', text: { en: 'A web shows several connected paths.', zhHant: '食物網顯示多條相連路徑。' } },
      { id: 'food-web-model-3', text: { en: 'More links can mean more possible effects when a population changes.', zhHant: '連結越多，族群改變時可能影響的範圍越大。' } },
    ],
    teacherNote: 'Ask students why a web is harder to predict than a chain. Expected idea: more connections.',
    sourceId: 'src-j2-ch2-ecosystems-ppt',
  },
  {
    id: 'j2-ch2-remove-producer',
    title: { en: 'Prediction: remove one producer', zhHant: '預測：移除一種生產者' },
    body: {
      en: 'If one producer decreases, organisms that feed on it may also decrease, and effects can spread through the food web.',
      zhHant: '如果一種生產者減少，吃它的生物也可能減少，影響會在食物網中擴散。',
    },
    visual: 'ecosystem',
    layout: 'comparison',
    emphasis: 'predict two consequences',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'remove-producer-1', text: { en: 'First consequence: fewer organisms can feed on that producer.', zhHant: '第一個結果：能以該生產者為食的生物變少。' } },
      { id: 'remove-producer-2', text: { en: 'Second consequence: predators may have less prey later.', zhHant: '第二個結果：掠食者之後可能有較少獵物。' } },
      { id: 'remove-producer-3', text: { en: 'Strong prediction names the link that changed.', zhHant: '好的預測會說出哪個連結改變了。' } },
    ],
    teacherNote: 'This preserves the recovered pilot teacher note. Give students time to predict two consequences before revealing examples.',
    sourceId: 'src-j2-ch2-ecosystems-pilot',
  },
  {
    id: 'j2-ch2-population-change',
    title: { en: 'Changes can spread', zhHant: '變化會擴散' },
    body: {
      en: 'A change in one population can affect several other organisms in the same food web.',
      zhHant: '一個族群的變化可能影響同一食物網中的多種其他生物。',
    },
    visual: 'ecosystem',
    layout: 'diagram',
    emphasis: 'one change, several effects',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'population-change-1', text: { en: 'Find the population that changed.', zhHant: '找出改變的族群。' } },
      { id: 'population-change-2', text: { en: 'Trace who eats it or depends on it.', zhHant: '追蹤誰吃它或依賴它。' } },
      { id: 'population-change-3', text: { en: 'Then trace the next feeding link.', zhHant: '再追蹤下一個覓食連結。' } },
    ],
    teacherNote: 'Recovered pilot wording preserved. Require students to point to arrows instead of giving unsupported guesses.',
    sourceId: 'src-j2-ch2-ecosystems-pilot',
  },
  {
    id: 'j2-ch2-ecosystem-balance',
    title: { en: 'Explain with evidence', zhHant: '用證據解釋' },
    body: {
      en: 'A good ecosystem explanation names the population change, the feeding link, and the predicted effect.',
      zhHant: '好的生態系解釋會說出族群變化、覓食連結和預測影響。',
    },
    visual: 'ecosystem',
    layout: 'question',
    emphasis: 'change + link + effect',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'ecosystem-balance-1', text: { en: 'Change: one population increases or decreases.', zhHant: '變化：一個族群增加或減少。' } },
      { id: 'ecosystem-balance-2', text: { en: 'Link: another organism feeds on it or competes with it.', zhHant: '連結：另一種生物以它為食或和它競爭。' } },
      { id: 'ecosystem-balance-3', text: { en: 'Effect: explain what may happen next.', zhHant: '影響：解釋接下來可能發生什麼。' } },
    ],
    teacherNote: 'Use this as the answer frame for the worksheet. Discourage one-word answers such as "bad" or "die".',
    sourceId: 'src-j2-ch2-ecosystems-pilot',
  },
  {
    id: 'j2-ch2-video-observation',
    title: { en: 'Video check: coastal seas', zhHant: '影片檢核：沿海海域' },
    body: {
      en: 'While watching the coastal seas clip, collect examples of organisms, habitat conditions and feeding interactions.',
      zhHant: '觀看沿海海域影片時，記錄生物、棲地條件和覓食互動的例子。',
    },
    visual: 'video',
    layout: 'question',
    emphasis: 'observe, classify, explain',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'video-observation-1', text: { en: 'Organism observed.', zhHant: '觀察到的生物。' } },
      { id: 'video-observation-2', text: { en: 'Habitat condition observed.', zhHant: '觀察到的棲地條件。' } },
      { id: 'video-observation-3', text: { en: 'Possible feeding interaction.', zhHant: '可能的覓食互動。' } },
    ],
    teacherNote: 'Use only observations students can support from the recovered video resource. Pause after each category if needed.',
    sourceId: 'src-j2-ch2-ecosystems-pilot',
  },
  {
    id: 'j2-ch2-food-web-exit',
    title: { en: 'Exit check: predict and justify', zhHant: '課堂檢核：預測並說明理由' },
    body: {
      en: 'Predict one effect of a population change in an aquatic food web, then justify it using a feeding link.',
      zhHant: '預測水域食物網中一個族群變化的影響，並使用一個覓食連結說明理由。',
    },
    visual: 'question',
    layout: 'question',
    emphasis: 'prediction + feeding link',
    revealMode: 'step-by-step',
    reveals: [
      { id: 'food-web-exit-1', text: { en: 'Name the population that changes.', zhHant: '說出改變的族群。' } },
      { id: 'food-web-exit-2', text: { en: 'Name the organism connected by feeding.', zhHant: '說出透過覓食相連的生物。' } },
      { id: 'food-web-exit-3', text: { en: 'Explain the predicted effect.', zhHant: '解釋預測的影響。' } },
    ],
    teacherNote: 'Collect one complete CER-style sentence: change, evidence from the feeding link, predicted effect.',
    sourceId: 'src-j2-ch2-ecosystems-pilot',
  },
]

export const j2PilotLessons: ScienceLesson[] = [
  {
    id: 'j2-aquatic-habitats',
    unitId: 'j2-fall-ecosystems',
    title: 'Aquatic Ecosystems and Habitat Factors',
    subtitle: 'Classifying biotic and abiotic factors in freshwater and marine habitats',
    year: 'J2',
    semester: 'Fall',
    chapter: ecosystemsSectionLabel,
    lessonOrder: 1,
    duration: 50,
    status: 'Published',
    updated: '13 August 2026',
    objectives: [
      'Identify freshwater and marine habitats as aquatic ecosystems.',
      'Classify habitat factors as biotic or abiotic.',
      'Explain how biotic and abiotic factors affect organism survival and growth.',
      'Use habitat evidence to explain why an organism is suited to an aquatic environment.',
    ],
    sourceReferences: j2EcosystemSources,
    slides: aquaticHabitatSlides,
    resources: ecosystemResources,
  },
  {
    id: 'j2-aquatic-food-webs',
    unitId: 'j2-fall-ecosystems',
    title: 'Aquatic Food Webs and Ecosystem Change',
    subtitle: 'Tracing feeding links to predict how population changes spread',
    year: 'J2',
    semester: 'Fall',
    chapter: ecosystemsSectionLabel,
    lessonOrder: 2,
    duration: 50,
    status: 'Published',
    updated: '13 August 2026',
    objectives: [
      'Describe a food web as connected feeding relationships among organisms.',
      'Identify producers and consumers in a simple aquatic feeding model.',
      'Predict how removing or reducing one population can affect other organisms.',
      'Justify a food-web prediction using a named feeding link.',
    ],
    sourceReferences: j2EcosystemSources,
    slides: aquaticFoodWebSlides,
    resources: ecosystemResources,
  },
]
